/* REPUBLIC: 543 simulation engine — generated by scripts/bundle-engine.cjs from src/. Do not edit by hand. */
(function(global){
  "use strict";
  var factories={
"core/careers.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dailyCharacterTick = dailyCharacterTick;
exports.evaluateMonthlyCareer = evaluateMonthlyCareer;
exports.respondToMissedPay = respondToMissedPay;
exports.grantRequest = grantRequest;
exports.denyRequest = denyRequest;
exports.evaluateMonthlyCareers = evaluateMonthlyCareers;
const math_1 = require("./math");
const relationships_1 = require("./relationships");
const characters_1 = require("./characters");
const roles_1 = require("./roles");
const id_1 = require("./id");
const people_rules_1 = require("../shared/people-rules");
function logCareerEvent(world, characterId, type, note) {
    world.characterEvents.push({ id: (0, id_1.makeWorldId)(world, "career"), characterId, date: world.date, type, note });
    if (world.characterEvents.length > 3000)
        world.characterEvents.splice(0, world.characterEvents.length - 3000);
}
/** The browser and core use the same daily wellbeing rule. The core records its consequences as memory and career events. */
function dailyCharacterTick(world, c, rng) {
    if (!c.employed)
        return;
    const update = (0, people_rules_1.dailyWellbeing)(c, world.date, () => rng.next());
    c.energy = update.energy;
    c.stress = update.stress;
    c.morale = update.morale;
    c.burnoutStreak = update.burnoutStreak;
    c.onLeaveUntil = update.onLeaveUntil;
    if (update.mistake) {
        world.organisation.credibility = (0, math_1.clamp)(world.organisation.credibility - .5);
        logCareerEvent(world, c.id, "mistake", "A stress-driven mistake affected the team's work.");
    }
    if (update.forcedLeave) {
        (0, relationships_1.remember)(world, c.id, "burnout", 65, "Burned out and took forced leave.", { emotionalValence: -40 });
        logCareerEvent(world, c.id, "burnout_leave", `Took leave until ${c.onLeaveUntil}.`);
    }
}
function monthsBetween(a, b) { const d1 = new Date(a + "T00:00:00Z"), d2 = new Date(b + "T00:00:00Z"); return (d2.getUTCFullYear() - d1.getUTCFullYear()) * 12 + (d2.getUTCMonth() - d1.getUTCMonth()); }
/** How much of their skill set a character brings to their current role; used to judge whether they have outgrown it. */
function bestSkill(c) { const values = Object.values(c.skills).filter((v) => typeof v === "number"); return values.length ? Math.max(...values) : 40; }
/** Deterministic monthly evolution: skills grow with use, requests surface from ambition, and resignation risk is scored from morale, loyalty, resentment and unmet requests. */
function evaluateMonthlyCareer(world, c, rng) {
    if (!c.employed)
        return;
    const rel = (0, relationships_1.getRelationship)(world, world.player.id, c.id) ?? { trust: 50, loyalty: 50, personal: 50, resentment: 0, fear: 0, ideologicalAlignment: 50, actorA: "", actorB: "" };
    const tenureMonths = monthsBetween(c.joinedOn || world.date, world.date);
    if (c.energy > 45 && rng.next() < .35 + c.psychology.ambition * .003) {
        const key = Object.entries(c.skills).sort((a, b) => (b[1] ?? 0) - (a[1] ?? 0))[0]?.[0] ?? "field";
        const gain = 1 + Math.round(rng.next() * 2);
        c.skills[key] = (0, math_1.clamp)((c.skills[key] ?? 40) + gain);
        logCareerEvent(world, c.id, "skill_growth", `${key} improved through active work.`);
    }
    let resignScore = 0;
    if (c.morale < 30)
        resignScore += 18;
    if (rel.resentment > 60)
        resignScore += 22;
    if (rel.loyalty < 25)
        resignScore += 16;
    if (c.psychology.ambition > 70 && (!c.roleId || c.roleId === "volunteer") && tenureMonths > 4)
        resignScore += 10;
    if (c.pendingRequest && monthsBetween(c.pendingRequest.askedOn, world.date) >= 2)
        resignScore += 14;
    resignScore -= rel.loyalty * .15 + rel.personal * .08;
    resignScore *= .4 + c.psychology.riskTolerance * .008;
    const resignProbability = (0, math_1.clamp)(resignScore, 0, 85) / 100;
    if (tenureMonths >= 1 && rng.next() < resignProbability) {
        resignCharacter(world, c, "Resigned after accumulated dissatisfaction.");
        return;
    }
    if (!c.pendingRequest && tenureMonths >= 2) {
        const wantsRaise = c.psychology.greed > 55 && c.psychology.ambition > 40;
        const wantsPromotion = c.psychology.ambition > 65 && bestSkill(c) >= 65 && (0, roles_1.roleLevel)(c.roleId) < 4;
        if (wantsPromotion && rng.next() < .05 + c.psychology.ambition * .002) {
            const target = (0, roles_1.nextRoleUp)(c.roleId);
            if (target)
                c.pendingRequest = { type: "promotion", askedOn: world.date, detail: `Believes they are ready for ${roles_1.ROLE_PROFILES[target].title}.`, targetRole: target };
        }
        else if (wantsRaise && rng.next() < .05 + c.psychology.greed * .0015) {
            const amount = Math.round(c.salaryMonthly * (.1 + c.psychology.greed * .002));
            c.pendingRequest = { type: "raise", askedOn: world.date, detail: "Asking for a salary increase.", amount };
        }
    }
}
/** Missed pay lands differently on every person: loyalty and a strong personal bond buy patience or unpaid solidarity; greed and a thin bond buy an early exit; anyone in between just quietly resents it. */
function respondToMissedPay(world, c, rng) {
    c.unpaidStreak = (c.unpaidStreak ?? 0) + 1;
    const rel = (0, relationships_1.getRelationship)(world, world.player.id, c.id) ?? { trust: 50, loyalty: 50, personal: 50, resentment: 0, fear: 0, ideologicalAlignment: 50, actorA: "", actorB: "" };
    c.morale = (0, math_1.clamp)(c.morale - 7);
    c.stress = (0, math_1.clamp)(c.stress + 5);
    const pResign = (0, math_1.clamp)((c.unpaidStreak - 1) * 15 + c.psychology.greed * .3 - rel.loyalty * .25, 0, 90) / 100;
    const pVolunteer = (0, math_1.clamp)(rel.loyalty * .5 + rel.personal * .3 - c.psychology.greed * .2, 0, 80) / 100;
    const roll = rng.next();
    if (roll < pResign) {
        resignCharacter(world, c, "Resigned after repeated missed salary.");
        (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { trust: -8, resentment: 14 });
        return "resigned";
    }
    if (roll < pResign + pVolunteer) {
        c.volunteer = true;
        (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { loyalty: 6, trust: 2 });
        (0, relationships_1.remember)(world, c.id, "support", 60, "Kept working unpaid while the organisation recovered.", { emotionalValence: 30 });
        logCareerEvent(world, c.id, "payroll_response", "Chose to volunteer through a payroll shortfall.");
        return "volunteered";
    }
    (0, relationships_1.remember)(world, c.id, "salary_missed", (0, math_1.clamp)(55 + c.unpaidStreak * 8), "The organisation could not fully meet payroll.", { emotionalValence: -(0, math_1.clamp)(35 + c.unpaidStreak * 6, 35, 80) });
    (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { trust: -4, resentment: 5, loyalty: -3 });
    logCareerEvent(world, c.id, "payroll_response", "Privately grew resentful over missed pay.");
    return "resentful";
}
function resignCharacter(world, c, note) {
    c.employed = false;
    c.pendingRequest = undefined;
    (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { loyalty: -6, personal: -4 });
    (0, relationships_1.remember)(world, c.id, "resignation", 72, note, { emotionalValence: -50 });
    logCareerEvent(world, c.id, "resignation", note);
}
function grantRequest(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    const req = c.pendingRequest;
    if (!req)
        throw new Error("No pending request");
    if (req.type === "raise") {
        c.salaryMonthly += req.amount ?? Math.round(c.salaryMonthly * .1);
        (0, relationships_1.remember)(world, c.id, "financial_favour", 50, "Was granted a requested raise.", { emotionalValence: 45 });
    }
    else if (req.type === "promotion" && req.targetRole) {
        (0, characters_1.assignRole)(world, c.id, req.targetRole);
        c.lastPromotionOn = world.date;
        (0, relationships_1.remember)(world, c.id, "promotion", 70, `Promoted to ${roles_1.ROLE_PROFILES[req.targetRole].title}.`, { emotionalValence: 65 });
    }
    else if (req.type === "ticket") {
        (0, relationships_1.remember)(world, c.id, "political_ticket", 75, "Was given a political ticket.", { emotionalValence: 70, politicalRelevance: 80 });
    }
    (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { trust: 8, loyalty: 10 });
    c.morale = (0, math_1.clamp)(c.morale + 10);
    c.pendingRequest = undefined;
}
/** A denial always costs something; how much depends on how proud and how ambitious the person is. */
function denyRequest(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    const req = c.pendingRequest;
    if (!req)
        throw new Error("No pending request");
    const sting = c.psychology.ego * .5 + c.psychology.ambition * .3;
    (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { trust: -(0, math_1.clamp)(6 + sting * .08, 6, 18), loyalty: -(0, math_1.clamp)(8 + sting * .1, 8, 22), resentment: (0, math_1.clamp)(10 + sting * .15, 10, 30) });
    c.morale = (0, math_1.clamp)(c.morale - 8);
    (0, relationships_1.remember)(world, c.id, "denied_request", (0, math_1.clamp)(55 + sting * .2), `Was denied a requested ${req.type}.`, { emotionalValence: -(0, math_1.clamp)(45 + sting * .2, 45, 90) });
    c.pendingRequest = undefined;
}
function evaluateMonthlyCareers(world, rng) {
    for (const c of Object.values(world.characters))
        evaluateMonthlyCareer(world, c, rng);
}

},
"core/characters.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hireCharacter = hireCharacter;
exports.fireCharacter = fireCharacter;
exports.assignRole = assignRole;
exports.restCharacter = restCharacter;
exports.workCharacter = workCharacter;
exports.effectiveSkill = effectiveSkill;
const math_1 = require("./math");
const relationships_1 = require("./relationships");
const roles_1 = require("./roles");
function hireCharacter(world, id, role, salaryMonthly, volunteer = false, roleId) {
    const c = world.characters[id];
    if (!c)
        throw new Error(`Unknown character ${id}`);
    c.role = role;
    c.salaryMonthly = volunteer ? 0 : salaryMonthly;
    c.volunteer = volunteer;
    c.employed = true;
    c.joinedOn = world.date;
    c.unpaidStreak = 0;
    if (roleId)
        c.roleId = roleId;
    (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, { trust: 3, loyalty: 4, personal: 2 });
    (0, relationships_1.remember)(world, c.id, "support", 45, volunteer ? "Joined as a volunteer." : "Accepted a paid role.", { emotionalValence: 35 });
}
/** High-ego, low-integrity characters remember being fired as a personal betrayal, not a business decision; steady, principled ones absorb it more calmly. */
function fireCharacter(world, id) {
    const c = world.characters[id];
    if (!c)
        throw new Error(`Unknown character ${id}`);
    const rel = (0, relationships_1.getRelationship)(world, world.player.id, c.id);
    const priorBond = rel ? (rel.trust + rel.loyalty + rel.personal) / 3 : 50;
    const egoFactor = c.psychology.ego / 50, bondFactor = priorBond / 50;
    c.employed = false;
    c.role = "Former staff";
    (0, relationships_1.adjustRelationship)(world, world.player.id, c.id, {
        trust: -(0, math_1.clamp)(14 * bondFactor, 6, 26),
        loyalty: -(0, math_1.clamp)(16 * bondFactor, 6, 28),
        resentment: (0, math_1.clamp)(18 * egoFactor, 8, 36),
        personal: -(0, math_1.clamp)(6 * bondFactor, 3, 14)
    });
    (0, relationships_1.remember)(world, c.id, "firing", (0, math_1.clamp)(70 + c.psychology.ego * .3), "Was removed from the organisation.", { emotionalValence: -(0, math_1.clamp)(60 + c.psychology.ego * .3, 60, 100) });
}
function assignRole(world, id, roleId) {
    const c = world.characters[id];
    if (!c)
        throw new Error(`Unknown character ${id}`);
    c.roleId = roleId;
    c.role = (0, roles_1.roleTitle)(roleId);
}
function restCharacter(c, amount = 18) { c.energy = (0, math_1.clamp)(c.energy + amount); c.stress = (0, math_1.clamp)(c.stress - amount * .45); }
function workCharacter(c, intensity) { c.energy = (0, math_1.clamp)(c.energy - intensity); c.stress = (0, math_1.clamp)(c.stress + intensity * .35); if (c.energy < 20)
    c.health = (0, math_1.clamp)(c.health - 1); }
function effectiveSkill(c, key) {
    const base = c.skills[key] ?? 20;
    const energyFactor = .55 + c.energy / 220;
    const stressPenalty = c.stress > 70 ? (c.stress - 70) * .35 : 0;
    return (0, math_1.clamp)(base * energyFactor - stressPenalty);
}

},
"core/commands.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.executeCommand = executeCommand;
const characters_1 = require("./characters");
const operations_1 = require("./operations");
const finance_1 = require("./finance");
const secrets_1 = require("./secrets");
const simulation_1 = require("./simulation");
const math_1 = require("./math");
const careers_1 = require("./careers");
const recruitment_1 = require("./recruitment");
const relationships_1 = require("./relationships");
const rng_1 = require("./rng");
function executeCommand(world, command) {
    switch (command.type) {
        case "HIRE_CHARACTER":
            (0, characters_1.hireCharacter)(world, command.characterId, command.role, command.salaryMonthly, command.volunteer ?? false, command.roleId);
            return { ok: true, message: `${world.characters[command.characterId].name} joined the organisation.` };
        case "FIRE_CHARACTER":
            (0, characters_1.fireCharacter)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name} was removed from the organisation.` };
        case "REST_PLAYER": {
            const days = Math.max(1, Math.min(7, command.days ?? 1));
            (0, characters_1.restCharacter)(world.player, 16 * days);
            world.player.sleepDebt = (0, math_1.clamp)(world.player.sleepDebt - 14 * days, 0, 100);
            world.organisation.mediaHeat = (0, math_1.clamp)(world.organisation.mediaHeat - days);
            return { ok: true, message: `Rested for ${days} day(s).`, reports: (0, simulation_1.advanceDays)(world, days) };
        }
        case "START_OPERATION": {
            const op = (0, operations_1.startOperation)(world, command.operation);
            return { ok: true, message: `Operation started: ${op.title}`, createdId: op.id };
        }
        case "RECEIVE_SMALL_DONATION":
            (0, finance_1.receiveDonation)(world, command.amount, command.recurringMonthly ?? 0);
            world.organisation.credibility = (0, math_1.clamp)(world.organisation.credibility + .5);
            return { ok: true, message: "Transparent donation recorded." };
        case "ACCEPT_HIDDEN_DONATION": {
            (0, finance_1.receiveDonation)(world, command.amount);
            const secret = (0, secrets_1.createSecret)(world, { kind: "hidden_donation", severity: (0, math_1.clamp)(35 + Math.log10(Math.max(1, command.amount)) * 8), witnessIds: command.intermediaryWitnessId ? [command.intermediaryWitnessId] : [], evidence: [{ kind: "transaction", label: "Undisclosed political contribution", confidence: .9 }] });
            return { ok: true, message: "Funds received. A hidden liability now exists.", createdId: secret.id };
        }
        case "SPEND_ORGANISATION":
            if (!(0, finance_1.spendOrganisation)(world, command.amount))
                return { ok: false, message: "Insufficient organisation funds." };
            return { ok: true, message: `₹${command.amount.toLocaleString("en-IN")} spent on ${command.purpose}.` };
        case "ADVANCE_DAYS": return { ok: true, message: `Advanced ${command.days} day(s).`, reports: (0, simulation_1.advanceDays)(world, command.days) };
        case "GRANT_REQUEST":
            (0, careers_1.grantRequest)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name}'s request was granted.` };
        case "DENY_REQUEST":
            (0, careers_1.denyRequest)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name}'s request was denied.` };
        case "REFRESH_RECRUITMENT":
            (0, recruitment_1.refreshRecruitmentPool)(world, (0, rng_1.createRng)(world.rngState + world.day), command.size ?? 3);
            return { ok: true, message: `${world.recruitmentPool.length} candidate(s) available.` };
        case "INTERVIEW_CANDIDATE":
            (0, recruitment_1.interviewCandidate)(world, command.candidateId, (0, rng_1.createRng)(world.rngState + world.day));
            return { ok: true, message: "Interview completed." };
        case "HIRE_CANDIDATE": {
            const hired = (0, recruitment_1.hireCandidate)(world, command.candidateId, command.role, command.salaryMonthly, command.volunteer ?? false);
            return { ok: true, message: `${hired.name} joined the organisation.`, createdId: hired.id };
        }
        case "DEFEND_PUBLICLY":
            (0, relationships_1.defendPublicly)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name} was defended publicly.` };
        case "HUMILIATE_PUBLICLY":
            (0, relationships_1.humiliatePublicly)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name} was publicly humiliated.` };
        case "PROVIDE_LEGAL_PROTECTION":
            (0, relationships_1.provideLegalProtection)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name} was given legal protection.` };
        case "RECOGNIZE_FOUNDING_MEMBER":
            (0, relationships_1.recognizeFoundingMember)(world, command.characterId);
            return { ok: true, message: `${world.characters[command.characterId].name} was recognised as a founding member.` };
    }
}

},
"core/elections.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.simulateConstituency = simulateConstituency;
exports.seatTally = seatTally;
const math_1 = require("./math");
function simulateConstituency(c, parties, ctx, rng) {
    const raw = {};
    for (const p of parties) {
        const baseline = c.partyBaseline[p.id] ?? p.baseSupport;
        const swing = ctx.nationalSwing[p.id] ?? 0;
        const org = ((ctx.organisationByParty[p.id] ?? p.nationalOrganisation) - 50) * .08;
        const cand = ((ctx.candidateStrength?.[c.id]?.[p.id] ?? 50) - 50) * .06;
        const noise = (rng.next() - .5) * c.volatility;
        raw[p.id] = Math.max(.1, baseline + swing + org + cand + noise);
    }
    const totalShare = Object.values(raw).reduce((a, b) => a + b, 0);
    const shares = Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, v / totalShare]));
    const turnout = (0, math_1.clamp)(c.turnoutBase + (rng.next() - .5) * 6, 35, 90) / 100, totalVotes = Math.round(c.electorate * turnout);
    const votes = Object.fromEntries(Object.entries(shares).map(([k, s]) => [k, Math.round(totalVotes * s)]));
    const winnerPartyId = Object.entries(votes).sort((a, b) => b[1] - a[1])[0][0];
    return { constituencyId: c.id, turnout, votes, winnerPartyId };
}
function seatTally(results) { return results.reduce((acc, r) => { acc[r.winnerPartyId] = (acc[r.winnerPartyId] ?? 0) + 1; return acc; }, {}); }

},
"core/finance.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.monthlyPayrollDue = monthlyPayrollDue;
exports.organisationMonthlyBurn = organisationMonthlyBurn;
exports.processMonthEnd = processMonthEnd;
exports.spendOrganisation = spendOrganisation;
exports.receiveDonation = receiveDonation;
const careers_1 = require("./careers");
function monthlyPayrollDue(world) {
    return Object.values(world.characters).filter(c => c.employed && !c.volunteer).reduce((sum, c) => sum + c.salaryMonthly, 0);
}
function organisationMonthlyBurn(world) {
    const f = world.organisation.finance;
    return monthlyPayrollDue(world) + f.monthlyOfficeCosts + f.monthlyTechnologyCosts + f.monthlyTravelBaseline;
}
/** Each unpaid character responds according to their own loyalty, greed and bond with the player, not a single organisation-wide penalty. */
function processMonthEnd(world, rng) {
    const f = world.organisation.finance;
    const payroll = monthlyPayrollDue(world);
    const fixed = f.monthlyOfficeCosts + f.monthlyTechnologyCosts + f.monthlyTravelBaseline;
    f.organisationCash += f.monthlyRecurringDonations;
    f.lifetimeRaised += f.monthlyRecurringDonations;
    const total = payroll + fixed + f.outstandingPayables;
    const paid = Math.min(total, f.organisationCash);
    f.organisationCash -= paid;
    f.lifetimeSpent += paid;
    const shortfall = total - paid;
    f.outstandingPayables = shortfall;
    if (shortfall > 0) {
        world.organisation.credibility = Math.max(0, world.organisation.credibility - 2);
        for (const c of Object.values(world.characters).filter(x => x.employed && !x.volunteer))
            (0, careers_1.respondToMissedPay)(world, c, rng);
    }
    else {
        for (const c of Object.values(world.characters).filter(x => x.employed))
            c.unpaidStreak = 0;
    }
    return { due: total, paid, shortfall };
}
function spendOrganisation(world, amount) {
    if (amount < 0)
        throw new Error("amount must be positive");
    if (world.organisation.finance.organisationCash < amount)
        return false;
    world.organisation.finance.organisationCash -= amount;
    world.organisation.finance.lifetimeSpent += amount;
    return true;
}
function receiveDonation(world, amount, recurringMonthly = 0) {
    if (amount < 0 || recurringMonthly < 0)
        throw new Error("donations cannot be negative");
    world.organisation.finance.organisationCash += amount;
    world.organisation.finance.lifetimeRaised += amount;
    world.organisation.finance.monthlyRecurringDonations += recurringMonthly;
}

},
"core/future.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateSystemEvent = generateSystemEvent;
const math_1 = require("./math");
const id_1 = require("./id");
function generateSystemEvent(world, rng) {
    const m = world.macro;
    const pressures = [
        { kind: "youth_protest", score: m.unemployment * .55 + (100 - m.institutionalTrust) * .25 + (100 - m.socialStability) * .2 },
        { kind: "cost_of_living_pressure", score: m.inflation * 7 + (100 - world.publicOpinion.workers) * .15 },
        { kind: "government_scandal", score: world.organisation.mediaHeat * .25 + world.organisation.legalExposure * .35 + Object.values(world.secrets).filter(s => !s.exposed).length * 6 },
        { kind: "party_faction_dispute", score: Math.max(0, 55 - world.organisation.credibility) * .7 + world.player.stress * .2 }
    ];
    const strongest = pressures.sort((a, b) => b.score - a.score)[0];
    const probability = (0, math_1.clamp)((strongest.score - 30) / 220, 0, .18);
    if (rng.next() > probability)
        return undefined;
    return { id: (0, id_1.makeWorldId)(world, "sys_evt"), date: world.date, kind: strongest.kind, payload: { severity: Math.round((0, math_1.clamp)(strongest.score, 10, 100)) } };
}

},
"core/id.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.makeId = makeId;
exports.resetIdCounter = resetIdCounter;
exports.hydrateWorldIdCounter = hydrateWorldIdCounter;
exports.makeWorldId = makeWorldId;
let legacyCounter = 0;
function makeId(prefix, seed = 0) { legacyCounter++; return `${prefix}_${seed.toString(36)}_${legacyCounter.toString(36)}`; }
function resetIdCounter() { legacyCounter = 0; }
function hydrateWorldIdCounter(world) {
    const ids = [world.player.id, ...Object.keys(world.characters), ...Object.keys(world.operations), ...Object.keys(world.evidence), ...world.evidenceEdges.map(x => x.id), ...Object.keys(world.secrets), ...world.memories.map(x => x.id), ...world.scheduledEvents.map(x => x.id), ...(world.characterEvents ?? []).map(x => x.id), ...(world.recruitmentPool ?? []).map(x => x.id)];
    const suffix = new RegExp(`_${world.seed.toString(36)}_([0-9a-z]+)$`);
    let highest = Math.max(1, world.idCounter ?? 1);
    for (const id of ids) {
        const match = id.match(suffix);
        if (match) {
            const value = parseInt(match[1], 36);
            if (Number.isFinite(value))
                highest = Math.max(highest, value);
        }
    }
    world.idCounter = highest;
    return highest;
}
function makeWorldId(world, prefix) {
    if (world.idCounter === undefined)
        hydrateWorldIdCounter(world);
    world.idCounter = (world.idCounter ?? 1) + 1;
    return `${prefix}_${world.seed.toString(36)}_${world.idCounter.toString(36)}`;
}

},
"core/math.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mean = exports.round = exports.clamp = void 0;
const clamp = (value, min = 0, max = 100) => Math.max(min, Math.min(max, value));
exports.clamp = clamp;
const round = (value, decimals = 0) => { const m = 10 ** decimals; return Math.round(value * m) / m; };
exports.round = round;
const mean = (values) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
exports.mean = mean;

},
"core/memory.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultDecay = defaultDecay;
exports.effectiveSalience = effectiveSalience;
exports.recallMemories = recallMemories;
exports.memoryWeight = memoryWeight;
const math_1 = require("./math");
function daysBetween(a, b) { return Math.max(0, Math.round((new Date(b + "T00:00:00Z").getTime() - new Date(a + "T00:00:00Z").getTime()) / 86400000)); }
/** Higher salience persists longer; a very high-salience memory never fully fades. */
function defaultDecay(salience) { return (0, math_1.clamp)(.2 + salience * .007, 0, .95); }
function effectiveSalience(memory, onDate) {
    const decay = memory.decay ?? defaultDecay(memory.salience);
    const halfLifeDays = 30 + decay * 700;
    const daysSince = daysBetween(memory.date, onDate);
    const decayed = memory.salience * Math.pow(.5, daysSince / halfLifeDays);
    const floor = memory.salience >= 80 ? memory.salience * .35 : 0;
    return (0, math_1.clamp)(Math.max(decayed, floor));
}
function recallMemories(world, characterId, opts = {}) {
    const min = opts.minEffectiveSalience ?? 0;
    return world.memories
        .filter(m => m.characterId === characterId && (!opts.type || m.type === opts.type) && (!m.involvedIds || m.involvedIds.includes(characterId) || m.characterId === characterId))
        .map(m => ({ ...m, effectiveSalience: effectiveSalience(m, world.date) }))
        .filter(m => m.effectiveSalience >= min)
        .sort((a, b) => b.effectiveSalience - a.effectiveSalience);
}
/** Net emotional weight of a character's remembered history: positive valence outweighs negative, scaled by how vivid each memory still is. */
function memoryWeight(world, characterId, type) {
    return recallMemories(world, characterId, { type }).reduce((sum, m) => sum + (m.emotionalValence ?? 0) * (m.effectiveSalience / 100), 0);
}

},
"core/operations.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.startOperation = startOperation;
exports.tickOperation = tickOperation;
const math_1 = require("./math");
const characters_1 = require("./characters");
const id_1 = require("./id");
const finance_1 = require("./finance");
const primarySkill = {
    protest: "field", school_audit: "research", public_investigation: "research", state_visit: "leadership", press_conference: "media", fundraising: "fundraising", recruitment: "leadership", legal_challenge: "legal", social_campaign: "media"
};
function startOperation(world, input) {
    if (input.budgetAllocated > world.organisation.finance.organisationCash)
        throw new Error("Insufficient organisation funds");
    const op = { ...input, id: (0, id_1.makeWorldId)(world, "op"), startedOn: world.date, progress: 0, spent: 0, status: "active" };
    world.operations[op.id] = op;
    return op;
}
function tickOperation(world, op, rng) {
    if (op.status !== "active")
        return 0;
    const staff = op.staffIds.map(id => world.characters[id]).filter(Boolean);
    const skill = primarySkill[op.kind];
    const staffPower = (0, math_1.mean)(staff.map(c => (0, characters_1.effectiveSkill)(c, skill)));
    const volunteerPower = Math.sqrt(Math.max(0, op.volunteerAllocation)) * 1.8;
    const budgetDaily = Math.min(Math.max(500, op.budgetAllocated / 20), Math.max(0, op.budgetAllocated - op.spent));
    if (budgetDaily > 0 && (0, finance_1.spendOrganisation)(world, budgetDaily)) {
        op.spent += budgetDaily;
    }
    const budgetPower = Math.log10(1 + budgetDaily) * 3;
    const noise = .8 + rng.next() * .4;
    let delta = (2 + staffPower * .045 + volunteerPower * .035 + budgetPower * .08) * noise;
    delta *= 1 - op.legalRisk / 250;
    delta = Math.max(.2, delta);
    op.progress = (0, math_1.clamp)(op.progress + delta, 0, op.targetProgress);
    op.publicMomentum = (0, math_1.clamp)(op.publicMomentum + delta * .35 - op.legalRisk * .003);
    op.mediaAttention = (0, math_1.clamp)(op.mediaAttention + delta * .2);
    for (const c of staff)
        (0, characters_1.workCharacter)(c, 2.5 + op.mediaAttention / 50);
    if (op.progress >= op.targetProgress) {
        op.status = "completed";
        world.organisation.credibility = (0, math_1.clamp)(world.organisation.credibility + 3);
        world.publicOpinion.youth = (0, math_1.clamp)(world.publicOpinion.youth + 2);
    }
    return delta;
}

},
"core/personal-life.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.personalLife = personalLife;
exports.isWorkday = isWorkday;
exports.planPersonalDay = planPersonalDay;
exports.resolvePersonalDay = resolvePersonalDay;
exports.settlePersonalMonth = settlePersonalMonth;
const math_1 = require("./math");
const relationships_1 = require("./relationships");
function personalLife(world) {
    return world.life ?? (world.life = { employment: world.player.profession.toLowerCase() === "unemployed" ? "unemployed" : "employed", attendedWorkDays: 0, missedWorkDays: 0, personalDebt: 0, familyTrust: 65 });
}
function isWorkday(date) {
    const day = new Date(date + "T00:00:00Z").getUTCDay();
    return day >= 1 && day <= 5;
}
function planPersonalDay(world, choice, delegateId) {
    const life = personalLife(world);
    if (life.planned?.date === world.date || life.lastResolvedDate === world.date)
        throw new Error("Today's personal commitment is already set");
    if (!["work", "movement", "delegate", "rest"].includes(choice))
        throw new Error("Unknown commitment");
    if (choice === "delegate" && (!delegateId || !world.characters[delegateId]))
        throw new Error("Choose an available colleague to delegate to");
    life.planned = { date: world.date, choice, delegateId };
}
/** A work shift is the default; political involvement costs work time unless delegated. */
function resolvePersonalDay(world) {
    const life = personalLife(world);
    if (life.lastResolvedDate === world.date)
        throw new Error("Personal day already resolved");
    const choice = life.planned?.date === world.date ? life.planned.choice : "work";
    const delegateId = life.planned?.date === world.date ? life.planned.delegateId : undefined;
    const shift = isWorkday(world.date) && life.employment === "employed";
    let note;
    if (choice === "work" || choice === "delegate") {
        if (shift) {
            life.attendedWorkDays++;
            world.player.jobStanding = (0, math_1.clamp)(world.player.jobStanding + .5);
            world.player.energy = (0, math_1.clamp)(world.player.energy - 1.5);
        }
        else
            world.player.energy = (0, math_1.clamp)(world.player.energy + 5);
        life.familyTrust = (0, math_1.clamp)(life.familyTrust + .2);
        note = shift ? "Attended the work shift." : "No scheduled work shift.";
        if (choice === "delegate") {
            const colleague = world.characters[delegateId];
            colleague.energy = (0, math_1.clamp)(colleague.energy - 6);
            colleague.stress = (0, math_1.clamp)(colleague.stress + 2);
            (0, relationships_1.adjustRelationship)(world, world.player.id, colleague.id, { trust: 2, loyalty: 1 });
            const memoryKey = `delegated_${colleague.id}_${world.date.slice(0, 7)}`;
            if (!world.flags[memoryKey]) {
                (0, relationships_1.remember)(world, colleague.id, "support", 55, "Trusted to lead while the player met personal obligations.");
                world.flags[memoryKey] = true;
            }
            note = "Attended work and delegated movement responsibility.";
        }
    }
    else if (choice === "movement") {
        if (shift) {
            life.missedWorkDays++;
            world.player.jobStanding = (0, math_1.clamp)(world.player.jobStanding - 4);
        }
        world.player.energy = (0, math_1.clamp)(world.player.energy - 5);
        world.player.stress = (0, math_1.clamp)(world.player.stress + 2);
        life.familyTrust = (0, math_1.clamp)(life.familyTrust - .7);
        world.organisation.volunteers += world.player.skills.leadership >= 55 ? 2 : 1;
        note = shift ? "Led the movement and missed a paid work shift." : "Led the movement on a day off.";
    }
    else {
        if (shift) {
            life.missedWorkDays++;
            world.player.jobStanding = (0, math_1.clamp)(world.player.jobStanding - 1);
        }
        world.player.energy = (0, math_1.clamp)(world.player.energy + 18);
        world.player.stress = (0, math_1.clamp)(world.player.stress - 7);
        life.familyTrust = (0, math_1.clamp)(life.familyTrust + 2);
        note = shift ? "Rested and missed a paid work shift." : "Rested on a day off.";
    }
    if (life.employment === "employed" && world.player.jobStanding < 15 && life.missedWorkDays >= 5) {
        life.employment = "unemployed";
        note += " Employment ended after repeated absence and poor standing.";
    }
    if (world.date === "2026-06-05")
        note += " A protest planning meeting and work obligation competed for the same day.";
    life.planned = undefined;
    life.lastResolvedDate = world.date;
    return note;
}
function settlePersonalMonth(world) {
    const life = personalLife(world), d = new Date(world.date + "T00:00:00Z");
    const last = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 0)).getUTCDate();
    let weekdays = 0;
    for (let day = 1; day <= last; day++)
        if (isWorkday(`${world.date.slice(0, 7)}-${String(day).padStart(2, "0")}`))
            weekdays++;
    const salary = Math.round(world.player.monthlyIncome * life.attendedWorkDays / weekdays);
    const costs = world.player.monthlyLivingCosts;
    const available = world.player.personalCash + salary;
    const paid = Math.min(available, costs);
    world.player.personalCash = available - paid;
    world.player.declaredAssets = world.player.personalCash;
    life.personalDebt += costs - paid;
    life.attendedWorkDays = 0;
    life.missedWorkDays = 0;
    return { salary, costs, newDebt: costs - paid };
}

},
"core/recruitment.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateCandidate = generateCandidate;
exports.refreshRecruitmentPool = refreshRecruitmentPool;
exports.interviewCandidate = interviewCandidate;
exports.assessCandidate = assessCandidate;
exports.hireCandidate = hireCandidate;
const math_1 = require("./math");
const id_1 = require("./id");
const characters_1 = require("./characters");
const FIRST_NAMES = ["Priya", "Arjun", "Neha", "Vikram", "Fatima", "Rahul", "Ananya", "Karan", "Divya", "Suresh", "Leela", "Imran"];
const LAST_NAMES = ["Sharma", "Iyer", "Khan", "Patil", "Reddy", "Bose", "Nair", "Singh", "Gupta", "Fernandes"];
const BACKGROUNDS = [
    "Spent years as a local trade-union organiser.", "Left a corporate finance job to join the movement.", "A former journalist covering state politics.",
    "Built a small NGO before it folded for lack of funds.", "Recently graduated, hungry to prove themselves.", "A retired schoolteacher with deep local contacts."
];
const HOME_STATES = ["Delhi", "Maharashtra", "Uttar Pradesh", "Kerala", "Karnataka", "Bihar", "West Bengal", "Rajasthan", "Tamil Nadu", "Gujarat"];
const SKILL_KEYS = ["communication", "strategy", "analysis", "leadership", "negotiation", "courage", "legal", "media", "finance", "research", "field", "fundraising"];
function band(value) { return value < 40 ? "weak" : value < 60 ? "average" : value < 80 ? "strong" : "excellent"; }
/** True stats stay hidden on the world object; only the derived impression is meant to reach the player. */
function generateCandidate(world, rng) {
    const name = `${rng.pick(FIRST_NAMES)} ${rng.pick(LAST_NAMES)}`;
    const skillCount = 2 + rng.integer(0, 2);
    const trueSkills = {};
    const pool = [...SKILL_KEYS];
    for (let i = 0; i < skillCount; i++) {
        const idx = rng.integer(0, pool.length - 1);
        const key = pool.splice(idx, 1)[0];
        trueSkills[key] = (0, math_1.clamp)(35 + rng.integer(0, 55));
    }
    const truePsychology = {
        ambition: (0, math_1.clamp)(rng.integer(20, 90)), integrity: (0, math_1.clamp)(rng.integer(15, 90)), greed: (0, math_1.clamp)(rng.integer(10, 85)),
        fear: (0, math_1.clamp)(rng.integer(10, 70)), ego: (0, math_1.clamp)(rng.integer(15, 90)), riskTolerance: (0, math_1.clamp)(rng.integer(15, 90)), ideologicalCommitment: (0, math_1.clamp)(rng.integer(20, 90))
    };
    return {
        id: (0, id_1.makeWorldId)(world, "candidate"), name, age: 22 + rng.integer(0, 28), homeState: rng.pick(HOME_STATES), background: rng.pick(BACKGROUNDS),
        trueSkills, truePsychology, interviewLevel: 0, generatedOn: world.date
    };
}
function refreshRecruitmentPool(world, rng, size = 3) {
    world.recruitmentPool = Array.from({ length: size }, () => generateCandidate(world, rng));
}
/** Interviewing narrows the noise on skill estimates and adds one qualitative concern the interviewer picked up on. */
function interviewCandidate(world, candidateId, rng) {
    const candidate = world.recruitmentPool.find(c => c.id === candidateId);
    if (!candidate)
        throw new Error("Unknown candidate");
    candidate.interviewLevel = Math.min(2, candidate.interviewLevel + 1);
}
/** What the player actually sees: qualitative impressions, not the true hidden numbers. Noise shrinks as interviewLevel rises. */
function assessCandidate(candidate, rng) {
    const noise = candidate.interviewLevel >= 2 ? 4 : candidate.interviewLevel === 1 ? 10 : 20;
    const estimatedSkills = {};
    for (const [key, value] of Object.entries(candidate.trueSkills)) {
        const observed = (0, math_1.clamp)(value + (rng.next() * 2 - 1) * noise);
        estimatedSkills[key] = band(observed);
    }
    const headline = [];
    const topSkill = Object.entries(candidate.trueSkills).sort((a, b) => (b[1] ?? 0) - (a[1] ?? 0))[0];
    if (topSkill && band(topSkill[1] ?? 0) !== "weak")
        headline.push(`${topSkill[1] >= 80 ? "Excellent" : "Strong"} ${topSkill[0]}.`);
    if (candidate.truePsychology.ambition > 70)
        headline.push("Very ambitious.");
    else if (candidate.truePsychology.ambition < 35)
        headline.push("Seems content staying in a supporting role.");
    const concerns = [];
    if (candidate.interviewLevel >= 1) {
        if (candidate.truePsychology.integrity < 35)
            concerns.push("References describe them as difficult to manage.");
        if (candidate.truePsychology.greed > 70)
            concerns.push("Seemed unusually focused on compensation.");
        if (candidate.truePsychology.ego > 75)
            concerns.push("Came across as hard to take direction from.");
    }
    if (candidate.interviewLevel >= 2 && candidate.truePsychology.riskTolerance > 75)
        concerns.push("Comfortable with tactics that carry real legal risk.");
    return { headline: headline.length ? headline : ["No strong impression either way."], estimatedSkills, concerns };
}
function hireCandidate(world, candidateId, role, salaryMonthly, volunteer = false) {
    const candidate = world.recruitmentPool.find(c => c.id === candidateId);
    if (!candidate)
        throw new Error("Unknown candidate");
    const id = (0, id_1.makeWorldId)(world, "staff");
    world.characters[id] = {
        id, name: candidate.name, age: candidate.age, role, homeState: candidate.homeState, background: candidate.background,
        salaryMonthly: 0, skills: candidate.trueSkills, energy: 80, health: 90, stress: 20, morale: 70,
        psychology: candidate.truePsychology, employed: false, volunteer: false, joinedOn: "", unpaidStreak: 0
    };
    (0, characters_1.hireCharacter)(world, id, role, salaryMonthly, volunteer);
    world.recruitmentPool = world.recruitmentPool.filter(c => c.id !== candidateId);
    return world.characters[id];
}

},
"core/relationships.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getRelationship = getRelationship;
exports.adjustRelationship = adjustRelationship;
exports.remember = remember;
exports.defendPublicly = defendPublicly;
exports.humiliatePublicly = humiliatePublicly;
exports.provideLegalProtection = provideLegalProtection;
exports.recognizeFoundingMember = recognizeFoundingMember;
const math_1 = require("./math");
const id_1 = require("./id");
const memory_1 = require("./memory");
function getRelationship(world, a, b) {
    return world.relationships.find(r => (r.actorA === a && r.actorB === b) || (r.actorA === b && r.actorB === a));
}
function adjustRelationship(world, a, b, delta) {
    let r = getRelationship(world, a, b);
    if (!r) {
        r = { actorA: a, actorB: b, trust: 50, loyalty: 50, personal: 50, ideologicalAlignment: 50, fear: 0, resentment: 0 };
        world.relationships.push(r);
    }
    for (const [k, v] of Object.entries(delta))
        if (typeof v === "number")
            r[k] = (0, math_1.clamp)(r[k] + v);
}
function remember(world, characterId, type, salience, note, extra = {}) {
    const memory = { id: (0, id_1.makeWorldId)(world, "mem"), characterId, date: world.date, type, salience: (0, math_1.clamp)(salience), note,
        involvedIds: extra.involvedIds, emotionalValence: extra.emotionalValence, decay: extra.decay ?? (0, memory_1.defaultDecay)((0, math_1.clamp)(salience)), politicalRelevance: extra.politicalRelevance };
    world.memories.push(memory);
    if (world.memories.length > 5000)
        world.memories.splice(0, world.memories.length - 5000);
    return memory;
}
/** A character defended in public: trust and loyalty rise, and the moment is remembered vividly for years. */
function defendPublicly(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    adjustRelationship(world, world.player.id, characterId, { trust: 10, loyalty: 8, personal: 4 });
    c.morale = (0, math_1.clamp)(c.morale + 6);
    remember(world, characterId, "support", 78, "Was publicly defended by the player.", { emotionalValence: 70, politicalRelevance: 40 });
}
/** Public humiliation is a high-salience wound: it scars trust immediately and resentment keeps building afterward. */
function humiliatePublicly(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    adjustRelationship(world, world.player.id, characterId, { trust: -16, loyalty: -10, resentment: 20, personal: -8 });
    c.morale = (0, math_1.clamp)(c.morale - 14);
    c.stress = (0, math_1.clamp)(c.stress + 10);
    remember(world, characterId, "humiliation", 90, "Was publicly humiliated by the player.", { emotionalValence: -85, politicalRelevance: 55 });
}
/** Legal protection during trouble is one of the strongest loyalty-building events in the game. */
function provideLegalProtection(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    adjustRelationship(world, world.player.id, characterId, { trust: 14, loyalty: 16, fear: -6 });
    remember(world, characterId, "legal_protection", 82, "Was protected by the player during legal trouble.", { emotionalValence: 75, politicalRelevance: 60 });
}
/** Recognising a founding member is a low-frequency, near-permanent morale and loyalty anchor. */
function recognizeFoundingMember(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    adjustRelationship(world, world.player.id, characterId, { trust: 6, loyalty: 10, personal: 6 });
    c.morale = (0, math_1.clamp)(c.morale + 10);
    remember(world, characterId, "founding_recognition", 88, "Was publicly recognised as a founding member.", { emotionalValence: 80, politicalRelevance: 30, decay: .9 });
}

},
"core/rng.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createRng = createRng;
function createRng(seed) {
    let s = seed >>> 0 || 0x6d2b79f5;
    return {
        next() { s |= 0; s = (s + 0x6d2b79f5) | 0; let t = Math.imul(s ^ (s >>> 15), 1 | s); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; },
        integer(min, max) { return Math.floor(this.next() * (max - min + 1)) + min; },
        pick(items) { if (!items.length)
            throw new Error("Cannot pick from empty array"); return items[this.integer(0, items.length - 1)]; },
        state() { return s >>> 0; }
    };
}

},
"core/roles.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROLE_PROFILES = void 0;
exports.roleLevel = roleLevel;
exports.roleTitle = roleTitle;
exports.nextRoleUp = nextRoleUp;
exports.roleFitScore = roleFitScore;
exports.ROLE_PROFILES = {
    founder: { id: "founder", title: "Founder / President", level: 5, primarySkill: "leadership", responsibilityWeight: 1.5 },
    chief_of_staff: { id: "chief_of_staff", title: "Chief of Staff", level: 4, primarySkill: "leadership", responsibilityWeight: 1.35 },
    general_secretary: { id: "general_secretary", title: "General Secretary", level: 4, primarySkill: "strategy", responsibilityWeight: 1.3 },
    legal_lead: { id: "legal_lead", title: "Legal Lead", level: 3, primarySkill: "legal", responsibilityWeight: 1.2 },
    research_lead: { id: "research_lead", title: "Research Lead", level: 3, primarySkill: "research", responsibilityWeight: 1.15 },
    media_lead: { id: "media_lead", title: "Media Lead", level: 3, primarySkill: "media", responsibilityWeight: 1.15 },
    finance_lead: { id: "finance_lead", title: "Finance Lead", level: 3, primarySkill: "finance", responsibilityWeight: 1.15 },
    field_organiser: { id: "field_organiser", title: "Field Organiser", level: 2, primarySkill: "field", responsibilityWeight: 1.05 },
    state_coordinator: { id: "state_coordinator", title: "State Coordinator", level: 2, primarySkill: "leadership", responsibilityWeight: 1.1 },
    district_coordinator: { id: "district_coordinator", title: "District Coordinator", level: 1, primarySkill: "field", responsibilityWeight: 1 },
    volunteer: { id: "volunteer", title: "Volunteer", level: 0, primarySkill: "field", responsibilityWeight: .6 }
};
function roleLevel(role) { return role ? exports.ROLE_PROFILES[role].level : 0; }
function roleTitle(role) { return role ? exports.ROLE_PROFILES[role].title : "Unassigned"; }
function nextRoleUp(role) {
    const level = roleLevel(role);
    const candidates = Object.values(exports.ROLE_PROFILES).filter(r => r.level === level + 1 && r.id !== "founder");
    if (!candidates.length)
        return undefined;
    candidates.sort((a, b) => b.responsibilityWeight - a.responsibilityWeight);
    return candidates[0].id;
}
/** A role's own skill counts double toward how well a character fills it. */
function roleFitScore(skills, role) {
    const profile = exports.ROLE_PROFILES[role];
    const primary = skills[profile.primarySkill] ?? 20;
    const others = Object.values(skills).filter((v) => typeof v === "number");
    const avgOther = others.length ? others.reduce((a, b) => a + b, 0) / others.length : 20;
    return primary * .65 + avgOther * .35;
}

},
"core/save.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CURRENT_SCHEMA_VERSION = void 0;
exports.serializeWorld = serializeWorld;
exports.deserializeWorld = deserializeWorld;
const personal_life_1 = require("./personal-life");
const id_1 = require("./id");
exports.CURRENT_SCHEMA_VERSION = 1;
function serializeWorld(world) { return JSON.stringify(world); }
function deserializeWorld(raw) {
    const parsed = JSON.parse(raw);
    if (parsed.schemaVersion !== exports.CURRENT_SCHEMA_VERSION)
        throw new Error(`Unsupported save schema ${parsed.schemaVersion}`);
    parsed.player.monthlyIncome ??= 35000;
    parsed.player.monthlyLivingCosts ??= 22000;
    parsed.player.jobStanding ??= 75;
    (0, personal_life_1.personalLife)(parsed);
    parsed.characterEvents ??= [];
    parsed.recruitmentPool ??= [];
    for (const c of Object.values(parsed.characters)) {
        c.psychology.ideologicalCommitment ??= 50;
        c.unpaidStreak ??= 0;
    }
    (0, id_1.hydrateWorldIdCounter)(parsed);
    return parsed;
}

},
"core/secrets.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createEvidence = createEvidence;
exports.createSecret = createSecret;
exports.tickSecretExposure = tickSecretExposure;
const math_1 = require("./math");
const id_1 = require("./id");
function createEvidence(world, caseId, kind, label, confidence = .75) {
    const id = (0, id_1.makeWorldId)(world, "evidence");
    world.evidence[id] = { id, caseId, kind, label, confidence: (0, math_1.clamp)(confidence, 0, 1), visibility: "private" };
    return id;
}
function createSecret(world, input) {
    const id = (0, id_1.makeWorldId)(world, "secret"), caseId = `case_${id}`;
    const evidenceIds = (input.evidence ?? []).map(e => createEvidence(world, caseId, e.kind, e.label, e.confidence));
    const s = { id, kind: input.kind, createdOn: world.date, severity: (0, math_1.clamp)(input.severity), exposureRisk: (0, math_1.clamp)(2 + input.severity * .12), legalRisk: (0, math_1.clamp)(input.severity * .75), politicalRisk: (0, math_1.clamp)(input.severity * .85), witnessIds: input.witnessIds ?? [], evidenceIds, exposed: false };
    world.secrets[id] = s;
    return s;
}
function tickSecretExposure(world, secret, rng) {
    if (secret.exposed)
        return { exposed: true, roll: 0, threshold: 1 };
    const evidencePressure = secret.evidenceIds.reduce((sum, id) => sum + (world.evidence[id]?.confidence ?? 0), 0);
    const threshold = (0, math_1.clamp)(secret.exposureRisk + evidencePressure + secret.witnessIds.length * .8 + world.organisation.mediaHeat * .018 + world.organisation.legalExposure * .014, 0, 70) / 1000;
    const roll = rng.next();
    if (roll < threshold) {
        secret.exposed = true;
        for (const id of secret.evidenceIds)
            if (world.evidence[id])
                world.evidence[id].visibility = "public";
        world.organisation.credibility = (0, math_1.clamp)(world.organisation.credibility - secret.politicalRisk * .18);
        world.organisation.legalExposure = (0, math_1.clamp)(world.organisation.legalExposure + secret.legalRisk * .25);
    }
    else
        secret.exposureRisk = (0, math_1.clamp)(secret.exposureRisk + .03 + evidencePressure * .01);
    return { exposed: secret.exposed, roll, threshold };
}

},
"core/signals.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.characterSignals = characterSignals;
exports.characterHeadline = characterHeadline;
const relationships_1 = require("./relationships");
const memory_1 = require("./memory");
/** Bands raw hidden numbers into player-facing language. The player never sees the underlying score, only which band it falls in. */
function characterSignals(world, characterId) {
    const c = world.characters[characterId];
    if (!c)
        throw new Error(`Unknown character ${characterId}`);
    const signals = [];
    if (c.energy < 25)
        signals.push("Seems exhausted.");
    else if (c.energy < 45)
        signals.push("Running low on energy.");
    if (c.stress > 75)
        signals.push("Under serious strain.");
    else if (c.stress > 55)
        signals.push("Increasingly frustrated.");
    if (c.health < 40)
        signals.push("Health may be suffering.");
    if (c.morale < 30)
        signals.push("Morale has fallen sharply.");
    else if (c.morale > 80)
        signals.push("Clearly energised by the work.");
    const rel = (0, relationships_1.getRelationship)(world, world.player.id, characterId);
    if (rel) {
        if (rel.trust > 78)
            signals.push("Strongly trusts you.");
        else if (rel.trust < 28)
            signals.push("Trust in you is thin.");
        if (rel.resentment > 55)
            signals.push("Relationship is strained.");
        if (rel.loyalty > 78)
            signals.push("Fiercely loyal.");
        else if (rel.loyalty < 25)
            signals.push("Loyalty seems shallow.");
        if (rel.personal > 75)
            signals.push("Considers you a close friend.");
    }
    if (c.psychology.ambition > 65 && (c.roleId === "volunteer" || !c.roleId))
        signals.push("May be seeking more responsibility.");
    if (c.psychology.ego > 70 && (rel?.resentment ?? 0) > 40)
        signals.push("Pride seems bruised.");
    if (c.psychology.integrity < 35 && c.psychology.greed > 60)
        signals.push("References describe them as difficult to manage.");
    if (c.psychology.riskTolerance > 75)
        signals.push("Comfortable taking risks others would avoid.");
    if ((c.unpaidStreak ?? 0) >= 2)
        signals.push("Has gone unpaid for some time.");
    const humiliations = (0, memory_1.recallMemories)(world, characterId, { type: "humiliation", minEffectiveSalience: 30 });
    if (humiliations.length)
        signals.push("Has not forgotten a past humiliation.");
    const netMood = (0, memory_1.memoryWeight)(world, characterId);
    if (netMood < -40)
        signals.push("Carries visible resentment from past events.");
    else if (netMood > 40)
        signals.push("Speaks warmly of their history with the movement.");
    return signals.length ? signals : ["Nothing unusual to report."];
}
/** A short human-readable line for a roster list, favouring the strongest available signal. */
function characterHeadline(world, characterId) {
    const signals = characterSignals(world, characterId);
    return signals[0];
}

},
"core/simulation.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.advanceOneDay = advanceOneDay;
exports.advanceDays = advanceDays;
const rng_1 = require("./rng");
const math_1 = require("./math");
const finance_1 = require("./finance");
const operations_1 = require("./operations");
const secrets_1 = require("./secrets");
const future_1 = require("./future");
const personal_life_1 = require("./personal-life");
const careers_1 = require("./careers");
function isoAddDay(date) { const d = new Date(`${date}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + 1); return d.toISOString().slice(0, 10); }
function isMonthEnd(date) { const d = new Date(`${date}T00:00:00Z`), t = new Date(d); t.setUTCDate(d.getUTCDate() + 1); return t.getUTCMonth() !== d.getUTCMonth(); }
function advanceOneDay(world) {
    const rng = (0, rng_1.createRng)(world.rngState), report = { date: world.date, operationUpdates: [], secretExposureChecks: [], triggeredEvents: [], notes: [] };
    report.notes.push((0, personal_life_1.resolvePersonalDay)(world));
    for (const op of Object.values(world.operations)) {
        const delta = (0, operations_1.tickOperation)(world, op, rng);
        if (delta > 0)
            report.operationUpdates.push({ id: op.id, progressDelta: delta, completed: op.status === "completed" });
    }
    for (const secret of Object.values(world.secrets)) {
        const result = (0, secrets_1.tickSecretExposure)(world, secret, rng);
        report.secretExposureChecks.push({ id: secret.id, ...result });
        if (result.exposed)
            report.notes.push(`Secret exposed: ${secret.kind}`);
    }
    const scheduled = world.scheduledEvents.filter(e => e.date === world.date);
    report.triggeredEvents.push(...scheduled);
    for (const event of scheduled) {
        if (event.kind === "historical_event") {
            if (!world.completedEventIds.includes(event.id))
                world.completedEventIds.push(event.id);
            world.flags[`historical_${event.id}`] = true;
            const flag = event.payload.anchorFlag;
            if (typeof flag === "string" && flag.startsWith("reported_"))
                world.flags[flag] = true;
            report.notes.push(`Historical anchor: ${event.payload.title}`);
        }
    }
    world.scheduledEvents = world.scheduledEvents.filter(e => e.date !== world.date);
    if (new Date(world.date) >= new Date(world.realWorldSnapshotDate)) {
        const ev = (0, future_1.generateSystemEvent)(world, rng);
        if (ev) {
            world.scheduledEvents.push(ev);
            report.notes.push(`Future event generated: ${ev.kind}`);
        }
    }
    if (isMonthEnd(world.date)) {
        report.payroll = (0, finance_1.processMonthEnd)(world, rng);
        (0, careers_1.evaluateMonthlyCareers)(world, rng);
        const personal = (0, personal_life_1.settlePersonalMonth)(world);
        report.notes.push(`Personal salary ${personal.salary}; living costs ${personal.costs}; new debt ${personal.newDebt}`);
    }
    world.player.energy = (0, math_1.clamp)(world.player.energy - 2.2 - world.player.stress * .012);
    world.player.stress = (0, math_1.clamp)(world.player.stress + .8 + (world.player.energy < 30 ? 1.8 : 0));
    world.player.sleepDebt = (0, math_1.clamp)(world.player.sleepDebt + .5, 0, 100);
    if (world.player.stress > 85 || world.player.energy < 12)
        world.player.health = (0, math_1.clamp)(world.player.health - .7);
    for (const c of Object.values(world.characters))
        (0, careers_1.dailyCharacterTick)(world, c, rng);
    world.day += 1;
    world.date = isoAddDay(world.date);
    world.player.level = 1 + Math.floor((world.day - 1) / 30);
    world.rngState = rng.state();
    report.date = world.date;
    return report;
}
function advanceDays(world, days) { if (days < 0 || days > 3660)
    throw new Error("days must be between 0 and 3660"); const reports = []; for (let i = 0; i < days; i++)
    reports.push(advanceOneDay(world)); return reports; }

},
"core/world.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createNewGame = createNewGame;
const math_1 = require("./math");
const traitSkills = {
    speaker: { communication: 18, courage: 7, analysis: -5 }, analyst: { analysis: 18, strategy: 8, communication: -4 }, organiser: { leadership: 17, strategy: 5, communication: 3 }, legal_mind: { analysis: 12, negotiation: 10, strategy: 4 }, outsider: { courage: 12, communication: 7, negotiation: -4 }, connector: { negotiation: 13, leadership: 8, strategy: 4 }
};
function skills(trait, points = {}) { const base = { communication: 45, strategy: 45, analysis: 45, leadership: 45, negotiation: 45, courage: 45 }; const allocated = Object.values(points ?? {}); if (allocated.some(n => !Number.isInteger(n) || n < 0) || allocated.reduce((a, b) => a + (b ?? 0), 0) > 12)
    throw new Error("Allocate at most 12 nonnegative skill points"); for (const [k, v] of Object.entries(traitSkills[trait]))
    base[k] = (0, math_1.clamp)(base[k] + v); for (const [k, v] of Object.entries(points ?? {})) {
    if (!(k in base))
        throw new Error("Unknown skill");
    base[k] = (0, math_1.clamp)(base[k] + v);
} return base; }
function friend(id, name, role, homeState, background, skills, integrity, ambition, ego, ideologicalCommitment) { return { id, name, age: 27, role, homeState, background, salaryMonthly: 0, skills, energy: 82, health: 92, stress: 18, morale: 80, psychology: { ambition, integrity, greed: 100 - integrity, fear: 30, ego, riskTolerance: 55, ideologicalCommitment }, employed: false, volunteer: false, joinedOn: "", foundingMember: true }; }
function createNewGame(opts) {
    const seed = opts.seed ?? 5432026, playerId = `player_${seed.toString(36)}_1`;
    const characters = {
        friend_asha: friend("friend_asha", "Asha Menon", "Friend · Law", "Kerala", "Practising lawyer since her mid-twenties; met the player at a legal-aid camp.", { legal: 74, analysis: 68, negotiation: 61 }, 86, 48, 40, 74),
        friend_rohan: friend("friend_rohan", "Rohan Verma", "Friend · Ground", "Uttar Pradesh", "Grew up organising college unions; restless without fieldwork.", { field: 78, leadership: 61, communication: 58 }, 62, 67, 58, 66),
        friend_meera: friend("friend_meera", "Meera Nair", "Friend · Media", "Delhi", "Former stringer for a regional paper, sharp instinct for a story.", { media: 81, communication: 73, research: 57 }, 76, 72, 52, 70),
        friend_sameer: friend("friend_sameer", "Sameer Khanna", "Friend · Business", "Maharashtra", "Runs a small logistics business; joined for the network, stayed for the cause.", { finance: 77, fundraising: 82, strategy: 63 }, 48, 84, 66, 38)
    };
    const savings = opts.personalSavings ?? 180000;
    if (!Number.isFinite(savings) || savings < 0)
        throw new Error("Savings must be nonnegative");
    return { schemaVersion: 1, seed, idCounter: 1, rngState: seed, date: "2026-05-14", realWorldSnapshotDate: opts.snapshotDate ?? "2026-09-25", day: 1, phase: "movement",
        player: { id: playerId, name: opts.name, age: opts.age, homeState: opts.homeState, profession: opts.profession, trait: opts.trait, gender: opts.gender, homeDistrict: opts.homeDistrict, education: opts.education, familyBackground: opts.familyBackground, monthlyIncome: opts.monthlyIncome ?? 35000, monthlyLivingCosts: opts.monthlyLivingCosts ?? 22000, jobStanding: 75, skills: skills(opts.trait, opts.skillPoints), energy: 84, health: 94, stress: 22, sleepDebt: 8, recognition: 0, level: 1, personalCash: savings, declaredAssets: savings, hiddenAssets: 0 },
        organisation: { id: "org_cjp", name: "CJP", abbreviation: "CJP", phase: "movement", credibility: 45, mediaHeat: 0, legalExposure: 0, volunteers: 0, members: 0, statePresence: {}, finance: { organisationCash: 0, monthlyRecurringDonations: 0, monthlyOfficeCosts: 0, monthlyTechnologyCosts: 0, monthlyTravelBaseline: 0, outstandingPayables: 0, lifetimeRaised: 0, lifetimeSpent: 0 } },
        characters, relationships: [], memories: [], operations: {}, evidence: {}, evidenceEdges: [], secrets: {},
        publicOpinion: { youth: 22, students: 27, urban: 9, rural: 3, women: 7, workers: 6, business: 2, national: 5, byState: { Delhi: 12, Maharashtra: 7, Kerala: 6 } },
        macro: { growth: 65, inflation: 48, unemployment: 58, fiscalPressure: 54, institutionalTrust: 51, socialStability: 67 },
        parties: {}, scheduledEvents: [], completedEventIds: [], flags: { historical_intro_complete: false, first_response: "unanswered" },
        characterEvents: [], recruitmentPool: [] };
}

},
"game/browser-bridge.js":function(module,exports,require){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEMOGRAPHICS = exports.BROWSER_SNAPSHOT_DATE = void 0;
exports.createBrowserWorld = createBrowserWorld;
exports.hydrateWorld = hydrateWorld;
exports.serialize = serialize;
exports.syncFromBrowser = syncFromBrowser;
exports.dailyPeopleTick = dailyPeopleTick;
exports.monthEnd = monthEnd;
exports.payrollDue = payrollDue;
exports.teamMoraleShift = teamMoraleShift;
exports.useStaff = useStaff;
exports.bribeAttempt = bribeAttempt;
exports.peopleView = peopleView;
exports.recruitmentView = recruitmentView;
exports.executePeopleCommand = executePeopleCommand;
exports.demographicIndex = demographicIndex;
exports.demographicsView = demographicsView;
exports.runCampaignAd = runCampaignAd;
exports.simulateNationalElection = simulateNationalElection;
const world_1 = require("../core/world");
const save_1 = require("../core/save");
const rng_1 = require("../core/rng");
const math_1 = require("../core/math");
const commands_1 = require("../core/commands");
const careers_1 = require("../core/careers");
const finance_1 = require("../core/finance");
const signals_1 = require("../core/signals");
const relationships_1 = require("../core/relationships");
const memory_1 = require("../core/memory");
const characters_1 = require("../core/characters");
const roles_1 = require("../core/roles");
const recruitment_1 = require("../core/recruitment");
const elections_1 = require("../core/elections");
exports.BROWSER_SNAPSHOT_DATE = "2026-09-28";
const TRAIT_MAP = { speaker: "speaker", analyst: "analyst", organiser: "organiser", lawyer: "legal_mind", outsider: "outsider", networker: "connector" };
const FRIEND_ROLES = { friend_asha: "legal_lead", friend_rohan: "field_organiser", friend_meera: "media_lead", friend_sameer: "finance_lead" };
const HIREABLE_ROLES = ["legal_lead", "research_lead", "media_lead", "finance_lead", "field_organiser", "state_coordinator", "district_coordinator"];
exports.DEMOGRAPHICS = ["youth", "students", "urban", "rural", "women", "workers", "business"];
const DEMOGRAPHIC_WEIGHTS = { youth: .2, students: .1, urban: .15, rural: .25, women: .15, workers: .1, business: .05 };
function createBrowserWorld(seed) {
    const world = (0, world_1.createNewGame)({ name: seed.name, age: seed.age, homeState: seed.homeState || "Delhi", profession: seed.profession || "Citizen", trait: TRAIT_MAP[seed.trait] ?? "speaker", seed: seed.seed, snapshotDate: exports.BROWSER_SNAPSHOT_DATE,
        gender: seed.gender, homeDistrict: seed.district, education: seed.education, familyBackground: seed.family, monthlyIncome: seed.monthlyIncome, personalSavings: seed.savings, monthlyLivingCosts: seed.monthlyLivingCosts });
    for (const [key, value] of Object.entries(seed.skills ?? {}))
        if (key in world.player.skills)
            world.player.skills[key] = (0, math_1.clamp)(value);
    world.organisation.name = "Cockroach Janta Party";
    world.flags.content_version = exports.BROWSER_SNAPSHOT_DATE;
    return world;
}
/** Restores defaults and the id counter exactly as a core save load would. */
function hydrateWorld(raw) { return (0, save_1.deserializeWorld)(typeof raw === "string" ? raw : JSON.stringify(raw)); }
function serialize(world) { return (0, save_1.serializeWorld)(world); }
/** The browser remains authoritative for organisation metrics; the world mirrors them before any engine step. */
function syncFromBrowser(world, snap) {
    world.date = snap.date;
    world.day = snap.day;
    world.player.name = snap.playerName;
    world.organisation.name = snap.orgName;
    world.organisation.finance.organisationCash = Math.max(0, snap.funds);
    world.organisation.volunteers = Math.max(0, snap.volunteers);
    world.organisation.credibility = (0, math_1.clamp)(snap.credibility);
    world.organisation.mediaHeat = (0, math_1.clamp)(snap.media);
    world.organisation.legalExposure = (0, math_1.clamp)(snap.legal);
}
function eventsSince(world, from) {
    return world.characterEvents.slice(from).map(e => ({ characterId: e.characterId, name: world.characters[e.characterId]?.name ?? "A colleague", type: e.type, note: e.note, date: e.date }));
}
/** One day of staff wellbeing: energy, stress, burnout leave and stress-driven mistakes. */
function dailyPeopleTick(world) {
    const rng = (0, rng_1.createRng)(world.rngState), mark = world.characterEvents.length, credibility = world.organisation.credibility;
    for (const c of Object.values(world.characters))
        (0, careers_1.dailyCharacterTick)(world, c, rng);
    world.rngState = rng.state();
    return { events: eventsSince(world, mark), credibilityDelta: world.organisation.credibility - credibility };
}
/** Month end for people: salaries from the remaining cash (each unpaid person responds individually), then careers evolve. */
function monthEnd(world, fundsAvailable) {
    const rng = (0, rng_1.createRng)(world.rngState), mark = world.characterEvents.length;
    const f = world.organisation.finance;
    f.organisationCash = Math.max(0, fundsAvailable);
    f.monthlyOfficeCosts = 0;
    f.monthlyTechnologyCosts = 0;
    f.monthlyTravelBaseline = 0;
    const credibility = world.organisation.credibility;
    const payroll = (0, finance_1.processMonthEnd)(world, rng);
    (0, careers_1.evaluateMonthlyCareers)(world, rng);
    world.rngState = rng.state();
    return { ...payroll, fundsAfter: f.organisationCash, events: eventsSince(world, mark), credibilityDelta: world.organisation.credibility - credibility };
}
function payrollDue(world) { return (0, finance_1.monthlyPayrollDue)(world) + world.organisation.finance.outstandingPayables; }
function activeStaff(world) {
    return Object.values(world.characters).filter(c => c.employed && !(c.onLeaveUntil && world.date < c.onLeaveUntil));
}
/** Choices that land on the whole team: everyone active feels it, and a large swing is remembered. */
function teamMoraleShift(world, delta, note) {
    const staff = activeStaff(world);
    for (const c of staff) {
        c.morale = (0, math_1.clamp)(c.morale + delta);
        if (Math.abs(delta) >= 4)
            (0, relationships_1.remember)(world, c.id, delta > 0 ? "support" : "overwork", (0, math_1.clamp)(40 + Math.abs(delta) * 4), note, { emotionalValence: (0, math_1.clamp)(delta * 8, -80, 80) });
    }
    return staff.length;
}
/** The best available colleague for a skill does the work: their skill becomes the action's bonus and the effort costs them energy. */
function useStaff(world, skill, intensity = 4) {
    const best = activeStaff(world).map(c => ({ c, score: (0, characters_1.effectiveSkill)(c, skill) })).sort((a, b) => b.score - a.score)[0];
    if (!best || best.score < 25)
        return { bonus: 0 };
    (0, characters_1.workCharacter)(best.c, intensity);
    return { bonus: Math.round((best.score - 25) / 5), id: best.c.id, name: best.c.name };
}
/** The network approaches the colleague it judges easiest to buy. Integrity and greed decide; the player only
 * learns that someone refused, or that a file leaked. */
function bribeAttempt(world) {
    const staff = activeStaff(world);
    if (!staff.length)
        return null;
    const rng = (0, rng_1.createRng)(world.rngState);
    const target = staff.sort((a, b) => (a.psychology.integrity - a.psychology.greed) - (b.psychology.integrity - b.psychology.greed))[0];
    const accepted = rng.next() < (0, math_1.clamp)((target.psychology.greed - target.psychology.integrity + 30) / 120, 0, .8);
    world.rngState = rng.state();
    if (accepted)
        (0, relationships_1.remember)(world, target.id, "betrayal", 75, "Took money to pass the movement's case files to the network.", { emotionalValence: -30, politicalRelevance: 80 });
    else {
        target.morale = (0, math_1.clamp)(target.morale + 5);
        (0, relationships_1.remember)(world, target.id, "support", 65, "Refused a bribe to betray the movement.", { emotionalValence: 55, politicalRelevance: 60 });
    }
    return { id: target.id, name: target.name, accepted };
}
function peopleView(world) {
    return Object.values(world.characters).map(c => {
        const onLeave = !!(c.employed && c.onLeaveUntil && world.date < c.onLeaveUntil);
        const status = onLeave ? "on_leave" : c.employed ? (c.volunteer ? "volunteer" : "paid") : c.joinedOn ? "former" : "available";
        const suggestedRole = FRIEND_ROLES[c.id] ?? bestRole(c.skills);
        return { id: c.id, name: c.name, role: c.employed ? c.role : status === "former" ? "Former colleague" : c.role, background: c.background ?? "", homeState: c.homeState ?? "", founding: !!c.foundingMember,
            status, salaryMonthly: c.salaryMonthly, suggestedRole, suggestedRoleTitle: (0, roles_1.roleTitle)(suggestedRole),
            signals: c.joinedOn ? (0, signals_1.characterSignals)(world, c.id) : [],
            memories: (0, memory_1.recallMemories)(world, c.id, { minEffectiveSalience: 25 }).slice(0, 2).map(m => m.note),
            request: c.pendingRequest ? { type: c.pendingRequest.type, detail: c.pendingRequest.detail } : undefined };
    });
}
function bestRole(skills) {
    return HIREABLE_ROLES.map(role => ({ role, score: (0, roles_1.roleFitScore)(skills, role) })).sort((a, b) => b.score - a.score)[0].role;
}
function hash(text) { let h = 2166136261; for (const ch of text) {
    h ^= ch.charCodeAt(0);
    h = Math.imul(h, 16777619);
} return h >>> 0; }
/** Impressions are stable between renders: the noise depends only on the candidate and how well they have been interviewed. */
function recruitmentView(world) {
    return world.recruitmentPool.map(candidate => {
        const impression = (0, recruitment_1.assessCandidate)(candidate, (0, rng_1.createRng)(hash(candidate.id) + candidate.interviewLevel * 7919));
        const role = bestRole(candidate.trueSkills);
        return { id: candidate.id, name: candidate.name, age: candidate.age, homeState: candidate.homeState, background: candidate.background, interviewLevel: candidate.interviewLevel,
            suggestedRole: role, suggestedRoleTitle: (0, roles_1.roleTitle)(role), ...impression };
    });
}
/** People commands go through the core command layer; paid hires receive their best-fit role. */
function executePeopleCommand(world, command) {
    if (command.type === "GIVE_TIME_OFF") {
        const c = world.characters[command.characterId];
        if (!c || !c.employed)
            throw new Error("Only a current colleague can take time off.");
        if (c.onLeaveUntil && world.date < c.onLeaveUntil)
            throw new Error(`${c.name} is already on leave.`);
        const d = new Date(world.date + "T00:00:00Z");
        d.setUTCDate(d.getUTCDate() + command.days);
        c.onLeaveUntil = d.toISOString().slice(0, 10);
        (0, characters_1.restCharacter)(c, 30);
        c.morale = (0, math_1.clamp)(c.morale + 6);
        c.burnoutStreak = 0;
        (0, relationships_1.remember)(world, c.id, "support", 50, "Was given time off to recover.", { emotionalValence: 40 });
        return { ok: true, message: `${c.name} is on leave until ${c.onLeaveUntil}.` };
    }
    if (command.type === "HIRE_CHARACTER") {
        const c = world.characters[command.characterId];
        if (!c)
            throw new Error("Unknown colleague.");
        if (c.employed)
            throw new Error(`${c.name} is already part of the team.`);
        const roleId = command.roleId ?? FRIEND_ROLES[c.id] ?? bestRole(c.skills);
        return (0, commands_1.executeCommand)(world, { ...command, role: roles_1.ROLE_PROFILES[roleId].title, roleId });
    }
    if (command.type === "HIRE_CANDIDATE") {
        const candidate = world.recruitmentPool.find(x => x.id === command.candidateId);
        if (!candidate)
            throw new Error("That candidate is no longer available.");
        const roleId = bestRole(candidate.trueSkills);
        const result = (0, commands_1.executeCommand)(world, { ...command, role: roles_1.ROLE_PROFILES[roleId].title });
        if (result.createdId)
            world.characters[result.createdId].roleId = roleId;
        return result;
    }
    return (0, commands_1.executeCommand)(world, command);
}
/** Opinion among voter groups, as a turnout-weighted national figure. */
function demographicIndex(world) {
    return exports.DEMOGRAPHICS.reduce((sum, key) => sum + world.publicOpinion[key] * DEMOGRAPHIC_WEIGHTS[key], 0);
}
function demographicsView(world) {
    return exports.DEMOGRAPHICS.map(key => ({ key, value: Math.round(world.publicOpinion[key]), weight: DEMOGRAPHIC_WEIGHTS[key] }));
}
/** A targeted ad moves one group; a weak or distrusted organisation gets a smaller shift and some backlash elsewhere. */
function runCampaignAd(world, segment, quality) {
    if (!exports.DEMOGRAPHICS.includes(segment))
        throw new Error("Choose a voter group.");
    const gain = Math.max(1, Math.round(2 + quality / 12 + world.organisation.credibility / 25));
    world.publicOpinion[segment] = (0, math_1.clamp)(world.publicOpinion[segment] + gain);
    if (world.organisation.credibility < 40) {
        const backlash = exports.DEMOGRAPHICS.find(k => k !== segment && world.publicOpinion[k] > 3);
        if (backlash) {
            world.publicOpinion[backlash] = (0, math_1.clamp)(world.publicOpinion[backlash] - 2);
            return { gain, backlash };
        }
    }
    return { gain };
}
/** Every one of the 543 seats is simulated by the core constituency model against three generic, fictional blocs. */
function simulateNationalElection(input) {
    const rng = (0, rng_1.createRng)(input.seed);
    const party = (id, name, base) => ({ id, name, abbreviation: id.toUpperCase(), nationalOrganisation: 50, funds: 0, leadershipStrength: 50, baseSupport: base });
    const parties = [party("player", input.partyName, 0), party("ruling", "Ruling alliance", 31), party("opposition", "Opposition alliance", 25), party("regional", "Regional and independent candidates", 14)];
    const swing = (0, math_1.clamp)(((input.demographicIndex ?? 13) - 13) * .2, -6, 8);
    const byState = {};
    let seats = 0, playerVotes = 0, totalVotes = 0, turnoutSum = 0, seatTotal = 0;
    for (const [name, count] of Object.entries(input.seatCounts)) {
        const strength = input.strengthByState[name] ?? 1;
        let won = 0, statePlayer = 0, stateTotal = 0;
        // Each state has its own political landscape: some are ruling-alliance strongholds, others belong to regional parties.
        const h = hash(name), ruling = 24 + h % 17, opposition = 18 + (h >>> 5) % 15, regional = 8 + (h >>> 10) % 23;
        for (let i = 0; i < count; i++) {
            const id = `${name}-${i + 1}`;
            const result = (0, elections_1.simulateConstituency)({ id, name: id, state: name, electorate: 1800000, turnoutBase: 66, partyBaseline: { player: strength, ruling, opposition, regional }, volatility: 18 }, parties, { nationalSwing: { player: swing }, organisationByParty: { player: 50, ruling: 50, opposition: 50, regional: 50 }, candidateStrength: { [id]: { player: input.candidateQuality?.[name] ?? 45 } } }, rng);
            if (result.winnerPartyId === "player")
                won++;
            const votes = Object.values(result.votes).reduce((a, b) => a + b, 0);
            statePlayer += result.votes.player;
            stateTotal += votes;
            turnoutSum += result.turnout;
            seatTotal++;
        }
        byState[name] = { won, total: count, strength: Math.round(strength * 10) / 10, voteShare: stateTotal ? Math.round(statePlayer / stateTotal * 1000) / 10 : 0 };
        seats += won;
        playerVotes += statePlayer;
        totalVotes += stateTotal;
    }
    return { seats, voteShare: totalVotes ? Math.round(playerVotes / totalVotes * 1000) / 10 : 0, turnout: seatTotal ? Math.round(turnoutSum / seatTotal * 1000) / 10 : 0, byState };
}

},
"shared/people-rules.js":function(module,exports,require){
/* Daily staff wellbeing rule shared by the browser and TypeScript simulation. */
(function(root,factory){
  const api=factory();
  if(typeof module==="object"&&module.exports)module.exports=api;
  if(root)root.RepublicPeopleRules=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const clamp=value=>Math.max(0,Math.min(100,value));
  const addDays=(date,days)=>{const d=new Date(date+"T00:00:00Z");d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);};
  function dailyWellbeing(input,date,next){
    const result={energy:input.energy,stress:input.stress,morale:input.morale,burnoutStreak:input.burnoutStreak||0,onLeaveUntil:input.onLeaveUntil,mistake:false,forcedLeave:false};
    if(!input.employed)return result;
    if(result.onLeaveUntil&&date<result.onLeaveUntil)return result;
    if(result.onLeaveUntil&&date>=result.onLeaveUntil)result.onLeaveUntil=undefined;
    result.energy=clamp(result.energy-1.2-result.stress*.006);
    result.stress=clamp(result.stress+.25);
    result.burnoutStreak=result.energy<20?result.burnoutStreak+1:0;
    if(result.energy<15)result.morale=clamp(result.morale-.8);
    if(result.stress>72&&next()<.03){result.morale=clamp(result.morale-3);result.mistake=true;}
    if(result.burnoutStreak>=6){
      result.onLeaveUntil=addDays(date,3+Math.round(next()*3));
      result.energy=clamp(result.energy+28);
      result.stress=clamp(result.stress-18);
      result.burnoutStreak=0;
      result.forcedLeave=true;
    }
    return result;
  }
  return {dailyWellbeing};
});

}
  };
  var cache={};
  function resolve(from,request){
    var parts=from.split('/');parts.pop();
    request.split('/').forEach(function(p){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);});
    var id=parts.join('/');
    return factories[id+'.js']?id+'.js':id+'/index.js';
  }
  function load(id){
    if(cache[id])return cache[id].exports;
    if(!factories[id])throw new Error('Engine module not found: '+id);
    var module=cache[id]={exports:{}};
    factories[id].call(module.exports,module,module.exports,function(request){return load(resolve(id,request));});
    return module.exports;
  }
  global.RepublicEngine=Object.freeze(load("game/browser-bridge.js"));
})(typeof globalThis!=='undefined'?globalThis:this);
