import type { HistoricalEventRecord, HistoricalOperationTemplate, SourceRecord } from "./types";

export const movementSources:SourceRecord[]=[
  {id:"ie_2026_06_06_permission",title:"Cockroach Janta Party gets permission for Jantar Mantar protest as Abhijeet Dipke lands in Delhi",publisher:"The Indian Express",url:"https://indianexpress.com/article/cities/delhi/cockroach-janta-party-abhijeet-dipke-delhi-airport-jantar-mantar-protest-10726512/",publishedOn:"2026-06-06",accessedOn:"2026-09-25"},
  {id:"ie_2026_06_07_expand",title:"Yesterday was a trailer… will hold protests across country if Dharmendra Pradhan doesn’t quit",publisher:"The Indian Express",url:"https://indianexpress.com/article/india/cockroach-janta-party-cjp-protest-dharmendra-pradhan-ultimatum-10728034/",publishedOn:"2026-06-07",accessedOn:"2026-09-25"},
  {id:"it_2026_06_20_clear",title:"Abhijeet Dipke refuses to leave as cops clear Jantar Mantar protest site after extension denial",publisher:"India Today",url:"https://www.indiatoday.in/india/story/cockroach-janta-party-protest-jantar-mantar-cjp-founder-abhijit-dipke-neet-paper-leak-education-minister-dharmendra-pradhan-delhi-police-2930592-2026-06-20",publishedOn:"2026-06-20",accessedOn:"2026-09-25"},
  {id:"it_2026_06_20_facilities",title:"No food, no water: Abhijeet Dipke accuses police of cracking down on CJP protest",publisher:"India Today",url:"https://www.indiatoday.in/india/story/delhi-jantar-mantar-protest-cjp-abhijeet-dipke-police-food-water-washroom-restrictions-2930759-2026-06-20",publishedOn:"2026-06-20",accessedOn:"2026-09-25"},
  {id:"it_2026_08_05_pressure_group",title:"Will work as pressure group: Abhijeet Dipke reveals Cockroach Party's plan",publisher:"India Today",url:"https://www.indiatoday.in/india/story/cockroach-janta-party-abhijeet-dipke-strategy-maharashtra-political-party-2963909-2026-08-05",publishedOn:"2026-08-05",accessedOn:"2026-09-25"},
  {id:"ie_2026_08_11_school_audit",title:"‘Audit on August 15’: CJP’s Abhijit Dipke launches village school campaign",publisher:"The Indian Express",url:"https://indianexpress.com/article/cities/pune/abhijeet-dipke-cjp-rural-government-schools-social-audit-august-15-10827853/",publishedOn:"2026-08-11",accessedOn:"2026-09-25"},
  {id:"it_2026_08_15_school_thik_karo",title:"School thik karo: CJP's Abhijeet Dipke's latest campaign over poor govt schools",publisher:"India Today",url:"https://www.indiatoday.in/india/story/school-thik-karo-abhijeet-dipke-government-schools-maharashtra-ptag-2971917-2026-08-15",publishedOn:"2026-08-15",accessedOn:"2026-09-25"},
  {id:"it_2026_08_22_latur_fir",title:"FIR against Abhijeet Dipke for entering schools in Latur, threatening teachers",publisher:"India Today",url:"https://www.indiatoday.in/india/story/abhijeet-dipke-maharashtra-latur-school-fir-cjp-fir-over-threats-teachers-2977633-2026-08-22",publishedOn:"2026-08-22",accessedOn:"2026-09-25"},
  {id:"ie_2026_08_22_rajasthan",title:"Abhijit Dipke warns of Jantar Mantar-like protest after CJP alleges Jaipur attack",publisher:"The Indian Express",url:"https://indianexpress.com/article/india/cjp-team-confronted-rajasthan-school-visit-jaipur-ranka-bjp-goons-10842871/",publishedOn:"2026-08-22",accessedOn:"2026-09-25"}
];

export const movementTimeline2026:HistoricalEventRecord[]=[
  {id:"cjp_2026_06_06_jantar_permission",date:"2026-06-06",title:"Jantar Mantar protest receives permission",summary:"CJP's first major on-ground protest proceeds at Jantar Mantar after Delhi Police permission is obtained.",status:"VERIFIED",sourceIds:["ie_2026_06_06_permission"],tags:["cjp","jantar_mantar","education","protest"],playable:false},
  {id:"cjp_2026_06_07_national_mobilisation",date:"2026-06-07",title:"Movement announces wider mobilisation",summary:"After the first Delhi protest, CJP announces plans to mobilise across India and return for further protests if its demands are not met.",status:"VERIFIED",sourceIds:["ie_2026_06_07_expand"],tags:["cjp","mobilisation","national_expansion"],playable:false},
  {id:"cjp_2026_06_20_extension_denied",date:"2026-06-20",title:"Protest extension denied",summary:"Delhi Police declines an extension request and moves to clear the protest site after the permitted period.",status:"OFFICIAL_RECORD",sourceIds:["it_2026_06_20_clear"],tags:["cjp","jantar_mantar","police","legal"],playable:false},
  {id:"cjp_2026_06_20_facility_allegations",date:"2026-06-20",title:"CJP alleges restrictions on basic facilities",summary:"Dipke alleges restrictions involving food, water, washrooms and lighting at the protest. These are allegations reported by the media, not established findings in this record.",status:"OFFICIAL_ALLEGATION",sourceIds:["it_2026_06_20_facilities"],tags:["cjp","police","allegation"],playable:false},
  {id:"cjp_2026_08_05_pressure_group",date:"2026-08-05",title:"CJP says it will remain a pressure group for now",summary:"At a strategy meeting, Dipke says CJP has no immediate plan to become a political party and will focus on pressure-group activity and expansion.",status:"VERIFIED",sourceIds:["it_2026_08_05_pressure_group"],tags:["cjp","strategy","organisation"],playable:false},
  {id:"cjp_2026_08_15_school_thik_karo",date:"2026-08-15",title:"School Thik Karo launches",summary:"CJP launches a social-audit campaign focused on conditions and basic amenities in government schools.",status:"VERIFIED",sourceIds:["ie_2026_08_11_school_audit","it_2026_08_15_school_thik_karo"],tags:["cjp","schools","social_audit","maharashtra"],playable:false},
  {id:"cjp_2026_08_22_latur_fir",date:"2026-08-22",title:"Police register case after Latur school visit",summary:"Police register an FIR after a schoolteacher's complaint. The complaint contains allegations against Dipke and associates; investigation is reported as ongoing.",status:"UNDER_INVESTIGATION",sourceIds:["it_2026_08_22_latur_fir"],tags:["cjp","latur","fir","legal"],playable:false},
  {id:"cjp_2026_08_22_rajasthan_confrontation",date:"2026-08-22",title:"Rajasthan school visit confrontation",summary:"Residents oppose a CJP team's school visit near Jaipur. CJP alleges its members were attacked and calls for action.",status:"DISPUTED",sourceIds:["ie_2026_08_22_rajasthan"],tags:["cjp","rajasthan","school","confrontation"],playable:false}
];

export const historicalOperationTemplates:HistoricalOperationTemplate[]=[
  {id:"op_jantar_01",eventId:"cjp_2026_06_06_jantar_permission",kind:"protest",title:"Jantar Mantar: First Ground Test",location:"New Delhi",suggestedBudget:35000,targetProgress:100,startingMediaAttention:35,startingLegalRisk:10,startingPublicMomentum:30},
  {id:"op_expand_01",eventId:"cjp_2026_06_07_national_mobilisation",kind:"recruitment",title:"Build the National Network",location:"India",suggestedBudget:60000,targetProgress:100,startingMediaAttention:28,startingLegalRisk:5,startingPublicMomentum:36},
  {id:"op_jantar_02",eventId:"cjp_2026_06_20_extension_denied",kind:"legal_challenge",title:"Hold the Protest Together",location:"New Delhi",suggestedBudget:45000,targetProgress:100,startingMediaAttention:52,startingLegalRisk:28,startingPublicMomentum:42},
  {id:"op_school_01",eventId:"cjp_2026_08_15_school_thik_karo",kind:"school_audit",title:"School Thik Karo",location:"Maharashtra",suggestedBudget:85000,targetProgress:100,startingMediaAttention:32,startingLegalRisk:12,startingPublicMomentum:38},
  {id:"op_latur_legal",eventId:"cjp_2026_08_22_latur_fir",kind:"legal_challenge",title:"The Latur FIR",location:"Latur, Maharashtra",suggestedBudget:70000,targetProgress:100,startingMediaAttention:48,startingLegalRisk:55,startingPublicMomentum:35},
  {id:"op_rajasthan_school",eventId:"cjp_2026_08_22_rajasthan_confrontation",kind:"state_visit",title:"Rajasthan: Escalate or Verify",location:"Jaipur, Rajasthan",suggestedBudget:75000,targetProgress:100,startingMediaAttention:44,startingLegalRisk:30,startingPublicMomentum:36}
];
