const core=require('../dist/src/core/index.js');
const opening=require('../dist/src/game/opening.js');
const {createRepublic543Game}=require('../dist/src/game/bootstrap.js');
const campaign=require('../dist/src/game/campaign-2026.js');
const {createRng}=require('../dist/src/core/rng.js');
function ok(condition,message){if(!condition)throw new Error(message);}
const w=core.createNewGame({name:'Test',age:28,homeState:'Kerala',profession:'Analyst',trait:'analyst',seed:543});
const same=core.createNewGame({name:'Test',age:28,homeState:'Kerala',profession:'Analyst',trait:'analyst',seed:543});
ok(JSON.stringify(w)===JSON.stringify(same),'new-game state must be deterministic');
ok(w.date==='2026-05-14'&&w.organisation.volunteers===0,'ordinary citizen opening');
opening.chooseFirstResponse(w,'organise');
ok(w.flags.first_response==='organise'&&w.memories[0].date==='2026-05-14','first response must persist');
core.advanceDays(w,2);
for(let i=0;i<3;i++)opening.raiseSmallDonations(w,8);
opening.prepareJantarMantar(w,'water');
ok(opening.jantarReadiness(w).gaps.includes('security'),'preparation gaps must be visible');
core.hireCharacter(w,'friend_rohan','Field Lead',60000);
const op=core.startOperation(w,{kind:'protest',title:'Test Protest',location:'Delhi',targetProgress:100,budgetAllocated:10000,staffIds:['friend_rohan'],volunteerAllocation:80,mediaAttention:10,legalRisk:5,publicMomentum:10});
core.advanceDays(w,5);ok(op.progress>0,'operations must progress');
const secret=core.createSecret(w,{kind:'hidden_donation',severity:70,witnessIds:['friend_sameer'],evidence:[{kind:'transaction',label:'Undisclosed transfer',confidence:.9}]});ok(secret.evidenceIds.length===1,'secret must create evidence');
const anchored=createRepublic543Game({name:'Anchor',age:25,homeState:'Delhi',profession:'Teacher',trait:'organiser'});
ok(anchored.scheduledEvents.some(e=>e.date==='2026-06-06'&&e.payload.playable===true),'June protest must be a playable historical anchor');
const field=createRepublic543Game({name:'Field',age:29,homeState:'Delhi',profession:'Teacher',trait:'organiser',seed:543});
opening.chooseFirstResponse(field,'organise');core.advanceDays(field,23);core.receiveDonation(field,45000);
for(const task of ['water','security','permissions'])opening.prepareJantarMantar(field,task);
const treasury=field.organisation.finance.organisationCash;
campaign.organiseProtestDay(field,'mobilise');
ok(field.organisation.finance.organisationCash<treasury&&campaign.campaign2026(field).crowdTrust>38,'safe preparation must affect the campaign');
let repeated=false;try{campaign.organiseProtestDay(field,'mobilise');}catch(e){repeated=true;}ok(repeated,'one field decision per day');
const unsafe=createRepublic543Game({name:'Unsafe',age:29,homeState:'Delhi',profession:'Teacher',trait:'organiser',seed:543});
opening.chooseFirstResponse(unsafe,'organise');core.advanceDays(unsafe,23);core.receiveDonation(unsafe,45000);
campaign.organiseProtestDay(unsafe,'mobilise');ok(campaign.campaign2026(unsafe).crowdTrust<38&&campaign.campaign2026(unsafe).legalPressure>0,'unsafe mobilisation must cost trust');
core.advanceDays(field,44);campaign.negotiate2026(field,{demand:'exam_reform',publicBriefing:true,pauseDemonstrations:true});
let anchor=false;while(field.date<='2026-07-25'){const report=campaign.advanceCampaignDay(field);anchor ||=report.triggeredEvents.some(e=>e.id==='cjp_2026_07_25_minister_resignation');}
ok(anchor&&field.flags.reported_ministerial_resignation===true,'documented outcome must fire independently of tactics');
const roundTrip=core.deserializeWorld(core.serializeWorld(w));ok(roundTrip.day===w.day,'save round-trip failed');
const parties=[{id:'a',name:'A',abbreviation:'A',nationalOrganisation:60,funds:1,leadershipStrength:50,baseSupport:40},{id:'b',name:'B',abbreviation:'B',nationalOrganisation:50,funds:1,leadershipStrength:50,baseSupport:35}];
const result=core.simulateConstituency({id:'x',name:'X',state:'S',electorate:1000000,turnoutBase:68,partyBaseline:{a:44,b:40},volatility:5},parties,{nationalSwing:{},organisationByParty:{}},createRng(10));ok(['a','b'].includes(result.winnerPartyId),'election must produce a winner');
const audit=require('../dist/src/game/school-audit.js');
const school=createRepublic543Game({name:'Auditor',age:28,homeState:'Maharashtra',profession:'Teacher',trait:'analyst',seed:543});
core.receiveDonation(school,50000);
assertAuditDate();
function assertAuditDate(){let blocked=false;try{audit.openSchoolAudit(school,{district:'Fictional district',claim:'Composite facility complaint',leadId:'friend_asha',travelBudget:6000});}catch(e){blocked=true;}ok(blocked,'school audit must wait for documented campaign start');}
school.date='2026-08-15';
const caseFile=audit.openSchoolAudit(school,{district:'Fictional district',claim:'Composite report of damaged facilities',leadId:'friend_asha',travelBudget:6000});
ok(caseFile.status==='UNVERIFIED'&&caseFile.fictionalComposite,'tip must remain a fictional unverified claim');
audit.addSchoolEvidence(school,caseFile.id,{kind:'document',label:'Invented inspection sheet',origin:'field_sheet_1',confidence:.85,supports:true});
audit.addSchoolEvidence(school,caseFile.id,{kind:'witness',label:'Fictional parent interview',origin:'interview_1',confidence:.8,supports:true});
let premature=false;try{audit.publishSchoolAudit(school,caseFile.id);}catch(e){premature=true;}ok(premature,'publication must require official response and legal review');
audit.requestSchoolResponse(school,caseFile.id);
audit.recordSchoolResponse(school,caseFile.id,'denied','Fictional authority disputes the description');
audit.reviewSchoolAudit(school,caseFile.id,'friend_asha');
ok(audit.publishSchoolAudit(school,caseFile.id)==='DISPUTED','denied claim remains disputed even with evidence');
ok(school.evidenceEdges.length===2,'evidence graph connects independent sources to claim');
const admitted=audit.openSchoolAudit(school,{district:'Other fictional district',claim:'Composite water supply complaint',leadId:'friend_rohan',travelBudget:5000});
audit.addSchoolEvidence(school,admitted.id,{kind:'document',label:'Fictional maintenance log',origin:'maintenance_2',confidence:.9,supports:true});
audit.addSchoolEvidence(school,admitted.id,{kind:'witness',label:'Fictional caretaker statement',origin:'caretaker_2',confidence:.85,supports:true});
audit.requestSchoolResponse(school,admitted.id);
audit.recordSchoolResponse(school,admitted.id,'acknowledged','Fictional authority confirms repair is needed');
audit.reviewSchoolAudit(school,admitted.id,'friend_asha');
ok(audit.publishSchoolAudit(school,admitted.id)==='VERIFIED','corroborated and acknowledged simulated case may be verified');
ok(core.deserializeWorld(core.serializeWorld(school)).schoolAudits[admitted.id].status==='VERIFIED','school audit must survive save round-trip');
const citizen=core.createNewGame({name:'Worker',age:27,homeState:'Kerala',profession:'Private-sector employee',trait:'organiser',monthlyIncome:44000,personalSavings:1000,monthlyLivingCosts:23000});
core.planPersonalDay(citizen,'movement');
let workReport=core.advanceOneDay(citizen);
ok(citizen.player.jobStanding<75&&citizen.life.missedWorkDays===1,'movement meeting must cost a work shift');
core.planPersonalDay(citizen,'delegate','friend_asha');
workReport=core.advanceOneDay(citizen);
ok(citizen.life.attendedWorkDays===1&&citizen.relationships.some(x=>x.actorB==='friend_asha'&&x.trust>50),'delegation must protect work and build trust');
let duplicate=false;core.planPersonalDay(citizen,'rest');try{core.planPersonalDay(citizen,'movement');}catch(e){duplicate=true;}ok(duplicate,'one personal commitment per day');
const baseCash=citizen.player.personalCash;
let monthReport;while(citizen.date<='2026-05-31')monthReport=core.advanceOneDay(citizen);
ok(citizen.player.personalCash>=0&&citizen.life.personalDebt>=0,'personal finances must settle without negative cash');
ok(monthReport.notes.some(n=>n.includes('Personal salary')),'month-end salary and living costs must be reported');
ok(citizen.player.personalCash!==baseCash||citizen.life.personalDebt>0,'personal finances must change after month end');
const legacy=JSON.parse(core.serializeWorld(citizen));delete legacy.life;delete legacy.player.monthlyIncome;
ok(core.deserializeWorld(JSON.stringify(legacy)).life&&core.deserializeWorld(JSON.stringify(legacy)).player.monthlyIncome===35000,'old saves must hydrate new personal fields');
console.log('REPUBLIC: 543 core smoke tests passed');


