const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=fs.readFileSync('game.js','utf8').replace(/init\(\);\s*$/,'');
const saved={};
const context={console,Date,Math,Intl,localStorage:{setItem:(key,value)=>{saved[key]=value;}},document:{querySelector:()=>({textContent:'',innerHTML:'',style:{},classList:{add(){},remove(){}}})},setTimeout:()=>0,clearTimeout:()=>{}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('data/reality/historical-scenes.js','utf8'),context);
vm.runInContext(source,context);
vm.runInContext(`state={date:'2026-06-06',day:1,phase:'movement',player:{name:'Test',energy:82,health:92,stress:24,level:1,recognition:11},org:{funds:42000,volunteers:136,staff:0,credibility:52,media:18,legal:8},support:22,general:5,followers:14300,operationProgress:18};renderGame=()=>{};ensureState();startProject('campus');`,context);
let state=vm.runInContext('state',context);
assert.equal(state.day,2);
assert.equal(state.org.volunteers,166);
assert.equal(state.projects[0].status,'completed');
vm.runInContext(`performAction('hire');`,context);
state=vm.runInContext('state',context);
assert.equal(state.org.monthlyBurn,21100);
assert.ok(saved['republic543-save']);
vm.runInContext(`state.phase='party';state.org.funds=500000;state.org.volunteers=600;state.org.credibility=70;state.player.energy=80;state.support=40;state.general=20;state.targetState='Kerala';`,context);
const before=JSON.stringify(vm.runInContext('simulateElection()',context));
assert.equal(JSON.stringify(vm.runInContext('simulateElection()',context)),before,'same save must yield same election');
vm.runInContext(`performAction('campaign');performAction('campaign');performAction('campaign');performAction('election');`,context);
state=vm.runInContext('state',context);
assert.equal(state.org.presence.Kerala,45);
const result=state.elections[0];
assert.equal(Object.values(result.byState).reduce((n,x)=>n+x.total,0),543);
assert.equal(Object.values(result.byState).reduce((n,x)=>n+x.won,0),result.seats);
assert.ok(result.byState.Kerala.strength>JSON.parse(before).byState.Kerala.strength);
vm.runInContext(`state.phase='government';state.org.funds=500000;performAction('services');`,context);
assert.equal(vm.runInContext('state.governance.publicServices',context),52);
vm.runInContext(`state.date='2026-05-14';state.day=1;state.flags.firstResponse=undefined;`,context);
assert.equal(vm.runInContext('nextDecision().id',context),'first-response');
vm.runInContext(`state.flags.firstResponse='Help students organise';state.date='2026-06-05';advanceDay();`,context);
state=vm.runInContext('state',context);
assert.equal(state.date,'2026-06-06');
assert.ok(state.pendingScenes.includes('cjp-jantar'));
assert.equal(vm.runInContext('REAL_SCENES.some(x=>x.id==="cjp-jantar"&&!x.archive&&x.choices.length===3)',context),true);
assert.equal(vm.runInContext('REAL_SCENES.every((x,i,a)=>i===0||a[i-1].date<=x.date)',context),true);
vm.runInContext(`state.date='2026-06-06';state.flags.firstResponse='Help students organise';state.player.trait='organiser';state.player.skills={...TRAIT_SKILLS.organiser};state.player.jobStanding=75;state.org.funds=50000;state.jantarTasks={water:true,security:true,permissions:true};state.jantarCampaign={days:0,crowdTrust:38,studentTrust:35,evidenceQuality:20,legalPressure:0,fatigue:0,offers:0};runCampaignDay('mobilise');`,context);
state=vm.runInContext('state',context);
assert.ok(state.jantarCampaign.crowdTrust>38 && state.org.funds===43500,'prepared mobilisation must improve crowd trust and spend cash');
assert.ok(state.player.jobStanding<75,'fieldwork must cost job standing');
assert.throws(()=>vm.runInContext("runCampaignDay('mobilise')",context),/already made/);
vm.runInContext(`state.jantarCampaign={days:0,crowdTrust:38,studentTrust:35,evidenceQuality:20,legalPressure:0,fatigue:0,offers:0};state.jantarTasks={};runCampaignDay('mobilise');`,context);
assert.ok(vm.runInContext('state.jantarCampaign.crowdTrust<38 && state.jantarCampaign.legalPressure>0',context),'unsafe mobilisation must lower trust');
vm.runInContext(`state.date='2026-07-21';chooseNegotiation('exam_reform',true,false);`,context);
assert.equal(vm.runInContext('state.jantarCampaign.negotiation.demand',context),'exam_reform');
const profile=vm.runInContext(`buildCitizenProfile({name:'Citizen',age:28,homeState:'Kerala',profession:'Analyst',trait:'analyst',monthlyIncome:50000,savings:25000,monthlyLivingCosts:30000,points:{analysis:8,communication:4}})`,context);
assert.equal(profile.skills.analysis,73);
assert.equal(profile.monthlyIncome,50000);
assert.throws(()=>vm.runInContext(`buildCitizenProfile({name:'Bad',age:28,trait:'speaker',monthlyIncome:1,savings:0,monthlyLivingCosts:0,points:{analysis:13}})`,context),/12 skill points/);
assert.notEqual(vm.runInContext('TRAIT_SKILLS.analyst.communication',context),vm.runInContext('TRAIT_SKILLS.speaker.communication',context));
console.log('Browser profile, campaign and historical dispatch checks passed.');


