const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=fs.readFileSync('game.js','utf8').replace(/init\(\);\s*$/,'');
const saved={};
const context={console,Date,Math,Intl,localStorage:{setItem:(key,value)=>{saved[key]=value;}},document:{querySelector:()=>({textContent:'',innerHTML:'',style:{},classList:{add(){},remove(){}}})},setTimeout:()=>0,clearTimeout:()=>{}};
vm.createContext(context);
vm.runInContext(source,context);
vm.runInContext(`state={date:'2026-06-06',day:1,phase:'movement',player:{name:'Test',energy:82,health:92,stress:24,level:1,recognition:11},org:{funds:42000,volunteers:136,staff:0,credibility:52,media:18,legal:8},support:22,general:5,followers:14300,operationProgress:18};renderGame=()=>{};ensureState();startProject('campus');`,context);
let state=vm.runInContext('state',context);
assert.equal(state.day,2);
assert.equal(state.org.volunteers,166);
assert.equal(state.projects[0].status,'completed');
vm.runInContext(`performAction('hire');`,context);
state=vm.runInContext('state',context);
assert.equal(state.org.monthlyBurn,21100);
assert.ok(saved['republic543-save']);
vm.runInContext(`state.phase='party';state.org.funds=500000;state.org.volunteers=600;state.org.credibility=70;state.player.energy=80;state.support=40;state.general=20;state.targetState='Kerala';`,context);
const before=JSON.stringify(vm.runInContext('simulateElection()',context));
assert.equal(JSON.stringify(vm.runInContext('simulateElection()',context)),before,'same save must yield same election');
vm.runInContext(`performAction('campaign');performAction('campaign');performAction('campaign');performAction('election');`,context);
state=vm.runInContext('state',context);
assert.equal(state.org.presence.Kerala,48);
const result=state.elections[0];
assert.equal(Object.values(result.byState).reduce((n,x)=>n+x.total,0),543);
assert.equal(Object.values(result.byState).reduce((n,x)=>n+x.won,0),result.seats);
assert.ok(result.byState.Kerala.strength>JSON.parse(before).byState.Kerala.strength);
vm.runInContext(`state.phase='government';state.org.funds=500000;performAction('services');`,context);
assert.equal(vm.runInContext('state.governance.publicServices',context),52);
console.log('Browser simulation checks passed.');
